Repository microsoft/mu_basecore, pull requests merged in 2022-12, with the labels that each got.

#198 Set EFI_MEMORY_XP as a required capability for PciHostBridge
  MdeModulePkg/Bus/Pci/PciHostBridgeDxe/PciHostBridge.c
Labels: impact:non-functional, type:bug, complexity:intermediate

#195 Fix missing logs from GenMake.py
  BaseTools/Source/Python/AutoGen/GenMake.py
Labels: language:python, impact:non-functional, type:bug

#200 Update FillInMemoryMap() to Ignore Regions of GCD Memory Type Non-Existent
  MdeModulePkg/Core/Dxe/Misc/MemoryProtectionSupport.c
Labels: impact:security

#188 Add debug messages for DHCP state changes, Tftp progress, and PxeBc progress.
  NetworkPkg/Dhcp4Dxe/Dhcp4Impl.c
  NetworkPkg/Dhcp4Dxe/Dhcp4Io.c
  NetworkPkg/Mtftp4Dxe/Mtftp4Impl.c
  NetworkPkg/Mtftp4Dxe/Mtftp4Rrq.c
  NetworkPkg/Mtftp4Dxe/Mtftp4Wrq.c
  NetworkPkg/UefiPxeBcDxe/PxeBcBoot.c
  NetworkPkg/UefiPxeBcDxe/PxeBcImpl.c
Labels: type:enhancement

#204 Plugin/CodeQL: Fix query specifier assignment
  .pytool/Plugin/CodeQL/CodeQlAnalyzePlugin.py
Labels: type:bug

#205 Plugin/CodeQL: Skip CodeQlBuildPlugin if --skipbuild is given
  .pytool/Plugin/CodeQL/CodeQlBuildPlugin.py
Labels: type:bug

#206 Plugin/CodeQL: Add an integration file
  .pytool/Plugin/CodeQL/integration/__init__.py
  .pytool/Plugin/CodeQL/integration/stuart_codeql.py
Labels: type:enhancement, impact:non-functional

#207 CodeQL plugin filter support [Rebase & FF]
  .pytool/Plugin/CodeQL/CodeQlAnalyzePlugin.py
  .pytool/Plugin/CodeQL/Readme.md
  .pytool/Plugin/CodeQL/analyze/__init__.py
  .pytool/Plugin/CodeQL/analyze/analyze_filter.py
  .pytool/Plugin/CodeQL/analyze/globber.py
Labels: type:enhancement, type:documentation

#212 [bug] Absolute path support for DscCompleteCheck
  .pytool/Plugin/DscCompleteCheck/DscCompleteCheck.py
Labels: type:bug

#215 Improve log messages for DependencyCheck, UncrustifyCheck, and SpellCheck (#115)
  .pytool/Plugin/DependencyCheck/DependencyCheck.py
  .pytool/Plugin/SpellCheck/SpellCheck.py
  .pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py
Labels: type:enhancement, impact:non-functional
