Repository microsoft/mu_basecore, pull requests merged in 2023-02, with the labels that each got.

#230 Add extra RestoreTpl() call in DiskIo to maintain TPL raise/restore symmetry
  MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIo.c
Labels: impact:non-functional

#248 .azurepipelines: Add support for new artifacts_identifier param
  .azurepipelines/Matrix-Build-Job-Clang.yml
  .azurepipelines/Matrix-Build-Job.yml
Labels: type:enhancement, impact:breaking-change, impact:non-functional

#229 Remove unnecessary TPL restore call
  MdeModulePkg/Core/Dxe/Image/Image.c
Labels: impact:non-functional

#246 CodeQLAnalyzePlugin: Look for filter patterns in "Filters"
  .pytool/Plugin/CodeQL/CodeQlAnalyzePlugin.py
Labels: impact:breaking-change, impact:non-functional

#251 Add CodeQL Stuart parameter to this repo
  .pytool/CISettings.py
Labels: type:enhancement, impact:non-functional

#254 Add varpolicy dynamic shell command
  ShellPkg/DynamicCommand/VariablePolicyDynamicCommand/VariablePolicyDynamicCommand.c
  ShellPkg/DynamicCommand/VariablePolicyDynamicCommand/VariablePolicyDynamicCommand.h
  ShellPkg/DynamicCommand/VariablePolicyDynamicCommand/VariablePolicyDynamicCommand.inf
  ShellPkg/DynamicCommand/VariablePolicyDynamicCommand/VariablePolicyDynamicCommand.uni
  ShellPkg/ShellPkg.dsc
Labels: impact:testing, type:feature-request

#264 CodeQlFilters.yml: Add UefiDevicePathLib filters
  CodeQlFilters.yml
Labels: impact:security, impact:non-functional

#265 CompilerPlugin: Fix typo
  .pytool/Plugin/CompilerPlugin/CompilerPlugin.py
Labels: impact:non-functional

#263 UefiCpuPkg: Additional CodeQL fixes
  MdePkg/Library/UefiDevicePathLib/DevicePathFromText.c
  UefiCpuPkg/Library/CpuCommonFeaturesLib/MachineCheck.c
  UefiCpuPkg/Library/CpuExceptionHandlerLib/PeiCpuException.c
  UefiCpuPkg/Library/RegisterCpuFeaturesLib/CpuFeaturesInitialize.c
  UefiCpuPkg/Library/RegisterCpuFeaturesLib/RegisterCpuFeaturesLib.c
  UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c
  UefiCpuPkg/PiSmmCpuDxeSmm/SmmProfile.c
  UefiCpuPkg/PiSmmCpuDxeSmm/X64/PageTbl.c
  UefiCpuPkg/PiSmmCpuDxeSmm/X64/SmmProfileArch.c
Labels: impact:security

#266 MdePkg: Additional CodeQL fixes
  MdePkg/Library/BasePeCoffLib/BasePeCoff.c
  MdePkg/Library/UefiPciSegmentLibPciRootBridgeIo/PciSegmentLib.c
Labels: impact:security

#261 NetworkPkg: Additional CodeQL Fixes
  CodeQlFilters.yml
  MdeModulePkg/Library/FileExplorerLib/FileExplorer.c
  NetworkPkg/Application/VConfig/VConfig.c
  NetworkPkg/Dhcp4Dxe/Dhcp4Impl.c
  NetworkPkg/DnsDxe/DnsImpl.c
  NetworkPkg/HttpBootDxe/HttpBootConfig.c
  NetworkPkg/HttpDxe/HttpsSupport.c
  NetworkPkg/HttpUtilitiesDxe/HttpUtilitiesDxe.c
  NetworkPkg/IScsiDxe/IScsiConfig.c
  NetworkPkg/IScsiDxe/IScsiIbft.c
  NetworkPkg/IScsiDxe/IScsiMisc.c
  NetworkPkg/Ip4Dxe/Ip4Config2Nv.c
  NetworkPkg/Ip4Dxe/Ip4Icmp.c
  NetworkPkg/Ip4Dxe/Ip4Input.c
  NetworkPkg/Ip6Dxe/Ip6ConfigNv.c
  NetworkPkg/Ip6Dxe/Ip6If.c
  NetworkPkg/Ip6Dxe/Ip6Input.c
  NetworkPkg/Ip6Dxe/Ip6Mld.c
  NetworkPkg/Ip6Dxe/Ip6Nd.c
  NetworkPkg/Ip6Dxe/Ip6Output.c
  NetworkPkg/Library/DxeHttpIoLib/DxeHttpIoLib.c
  NetworkPkg/Library/DxeHttpLib/DxeHttpLib.c
  NetworkPkg/MnpDxe/MnpConfig.c
  NetworkPkg/MnpDxe/MnpIo.c
  NetworkPkg/MnpDxe/MnpVlan.c
  NetworkPkg/Mtftp4Dxe/Mtftp4Rrq.c
  NetworkPkg/Mtftp4Dxe/Mtftp4Support.c
  NetworkPkg/Mtftp4Dxe/Mtftp4Wrq.c
  NetworkPkg/Mtftp6Dxe/Mtftp6Rrq.c
  NetworkPkg/Mtftp6Dxe/Mtftp6Support.c
  NetworkPkg/Mtftp6Dxe/Mtftp6Wrq.c
  NetworkPkg/TcpDxe/SockImpl.c
  NetworkPkg/TcpDxe/TcpInput.c
  NetworkPkg/TcpDxe/TcpMisc.c
  NetworkPkg/TcpDxe/TcpOutput.c
  NetworkPkg/TlsAuthConfigDxe/TlsAuthConfigImpl.c
  NetworkPkg/TlsDxe/TlsDriver.c
  NetworkPkg/Udp4Dxe/Udp4Impl.c
  NetworkPkg/Udp4Dxe/Udp4Main.c
  NetworkPkg/VlanConfigDxe/VlanConfigImpl.c
Labels: impact:security, impact:non-functional

#273 MdeModulePkg: Additional codeql fixes
  CodeQlFilters.yml
  MdeModulePkg/Application/BootManagerMenuApp/BootManagerMenu.c
  MdeModulePkg/Application/CapsuleApp/CapsuleDump.c
  MdeModulePkg/Application/CapsuleApp/CapsuleOnDisk.c
  MdeModulePkg/Application/MpServicesTest/Options.c
  MdeModulePkg/Application/SmiHandlerProfileInfo/SmiHandlerProfileInfo.c
  MdeModulePkg/Application/UiApp/FrontPage.c
  MdeModulePkg/Bus/Ata/AtaAtapiPassThru/IdeMode.c
  MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressPassthru.c
  MdeModulePkg/Bus/Pci/NvmExpressPei/NvmExpressPeiHci.c
  MdeModulePkg/Bus/Pci/NvmExpressPei/NvmExpressPeiPassThru.c
  MdeModulePkg/Bus/Pci/PciBusDxe/PciResourceSupport.c
  MdeModulePkg/Bus/Pci/PciSioSerialDxe/Serial.c
  MdeModulePkg/Bus/Pci/PciSioSerialDxe/SerialIo.c
  MdeModulePkg/Bus/Pci/SdMmcPciHcDxe/SdMmcPciHci.c
  MdeModulePkg/Bus/Sd/EmmcBlockIoPei/EmmcHci.c
  MdeModulePkg/Bus/Ufs/UfsBlockIoPei/UfsHci.c
  MdeModulePkg/Core/Dxe/Hand/Handle.c
  MdeModulePkg/Core/Pei/Dispatcher/Dispatcher.c
  MdeModulePkg/Core/Pei/FwVol/FwVol.c
  MdeModulePkg/Core/PiSmmCore/Page.c
  MdeModulePkg/Core/PiSmmCore/SmiHandlerProfile.c
  MdeModulePkg/Core/PiSmmCore/SmramProfileRecord.c
  MdeModulePkg/Library/BootMaintenanceManagerUiLib/BootMaintenance.c
  MdeModulePkg/Library/BootMaintenanceManagerUiLib/BootMaintenanceManagerCustomizedUiSupport.c
  MdeModulePkg/Library/BootMaintenanceManagerUiLib/ConsoleOption.c
  MdeModulePkg/Library/BootMaintenanceManagerUiLib/Variable.c
  MdeModulePkg/Library/BootManagerUiLib/BootManager.c
  MdeModulePkg/Library/BrotliCustomDecompressLib/BrotliDecompress.c
  MdeModulePkg/Library/DeviceManagerUiLib/DeviceManager.c
  MdeModulePkg/Library/FileExplorerLib/FileExplorer.c
  MdeModulePkg/Library/UefiBootManagerLib/BmConsole.c
  MdeModulePkg/Universal/Acpi/AcpiTableDxe/AmlNamespace.c
  MdeModulePkg/Universal/CapsulePei/UefiCapsule.c
  MdeModulePkg/Universal/Console/TerminalDxe/Terminal.c
  MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskImpl.c
  MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskProtocol.c
  MdeModulePkg/Universal/FaultTolerantWriteDxe/FtwMisc.c
  MdeModulePkg/Universal/FvSimpleFileSystemDxe/FvSimpleFileSystem.c
  MdeModulePkg/Universal/HiiDatabaseDxe/Database.c
  MdeModulePkg/Universal/PCD/Dxe/Pcd.c
  MdeModulePkg/Universal/PlatformDriOverrideDxe/PlatDriOverrideDxe.c
  MdeModulePkg/Universal/PlatformDriOverrideDxe/PlatDriOverrideLib.c
  MdeModulePkg/Universal/RegularExpressionDxe/RegularExpressionDxe.c
  MdeModulePkg/Universal/SectionExtractionPei/SectionExtractionPei.c
  MdeModulePkg/Universal/SetupBrowserDxe/Expression.c
  MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c
  MdeModulePkg/Universal/SetupBrowserDxe/Presentation.c
  MdeModulePkg/Universal/SetupBrowserDxe/Setup.c
  MdeModulePkg/Universal/SmmCommunicationBufferDxe/SmmCommunicationBufferDxe.c
Labels: impact:security

#268 ShellPkg: Additional CodeQL fixes
  CodeQlFilters.yml
  MdePkg/Include/IndustryStandard/PciExpress21.h
  ShellPkg/Application/Shell/Shell.c
  ShellPkg/Application/Shell/ShellManParser.c
  ShellPkg/Application/Shell/ShellParametersProtocol.c
  ShellPkg/Application/Shell/ShellProtocol.c
  ShellPkg/DynamicCommand/HttpDynamicCommand/Http.c
  ShellPkg/DynamicCommand/TftpDynamicCommand/Tftp.c
  ShellPkg/Library/UefiHandleParsingLib/UefiHandleParsingLib.c
  ShellPkg/Library/UefiShellBcfgCommandLib/UefiShellBcfgCommandLib.c
  ShellPkg/Library/UefiShellCommandLib/UefiShellCommandLib.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/Comp.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/Dblk.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/Edit/Edit.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/EfiCompress.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/EfiDecompress.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/HexEdit/FileImage.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/LoadPciRom.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/Mm.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/Mode.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/Pci.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/SerMode.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/SetSize.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/SetVar.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/UefiShellDebug1CommandsLib.c
  ShellPkg/Library/UefiShellDriver1CommandsLib/Connect.c
  ShellPkg/Library/UefiShellDriver1CommandsLib/Dh.c
  ShellPkg/Library/UefiShellDriver1CommandsLib/Disconnect.c
  ShellPkg/Library/UefiShellDriver1CommandsLib/DrvCfg.c
  ShellPkg/Library/UefiShellDriver1CommandsLib/DrvDiag.c
  ShellPkg/Library/UefiShellDriver1CommandsLib/OpenInfo.c
  ShellPkg/Library/UefiShellLevel1CommandsLib/For.c
  ShellPkg/Library/UefiShellLevel1CommandsLib/Goto.c
  ShellPkg/Library/UefiShellLevel1CommandsLib/If.c
  ShellPkg/Library/UefiShellLevel1CommandsLib/Shift.c
  ShellPkg/Library/UefiShellLevel2CommandsLib/Cd.c
  ShellPkg/Library/UefiShellLevel2CommandsLib/Ls.c
  ShellPkg/Library/UefiShellLevel2CommandsLib/Map.c
  ShellPkg/Library/UefiShellLevel2CommandsLib/Parse.c
  ShellPkg/Library/UefiShellLevel2CommandsLib/Rm.c
  ShellPkg/Library/UefiShellNetwork2CommandsLib/Ifconfig6.c
Labels: impact:security

#271 Bugfix: Initialize EFI_STATUS in EfiBootManagerUpdateConsoleVariable()
  MdeModulePkg/Library/UefiBootManagerLib/BmConsole.c
Labels: impact:non-functional, type:bug

#279 CryptoPkg: Additional CodeQL fixes
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/Pkcs5Pbkdf2Tests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/RsaPkcs7Tests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/RsaPssTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/RsaTests.c
Labels: impact:non-functional

#283 Correct placement of DEBUG print
  MdeModulePkg/Bus/Pci/PciBusDxe/PciEnumeratorSupport.c
Labels: impact:non-functional

#284 MdeModulePkg/UefiBootManagerLib: Fix Previous CodeQL fix
  MdeModulePkg/Library/UefiBootManagerLib/BmConsole.c
Labels: complexity:easy, type:bug

#285 [cherry-pick] BaseTools/Plugin: Add coverage support for Unit Test
  BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
Labels: language:python
