Repository microsoft/mu_basecore, pull requests merged in 2023-08, with the labels that each got.

#507 Set OpenCppCoverage working dir to avoid files in root
  BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
Labels: language:python, impact:non-functional

#511 FlattenPdbs: improve performance
  BaseTools/Plugin/FlattenPdbs/FlattenPdbs.py
Labels: language:python, impact:non-functional

#512 WinRcPath: improve performance
  BaseTools/Plugin/WindowsResourceCompiler/WinRcPath.py
Labels: language:python, impact:non-functional

#519 BaseTools: Rust support enhancements
  BaseTools/Conf/build_rule.template
  BaseTools/Conf/tools_def.template
  Docs/rust_build.md
  Makefile.toml
Labels: impact:non-functional

#527 FlattenPdbs.py: Support python 3.9
  BaseTools/Plugin/FlattenPdbs/FlattenPdbs.py
Labels: language:python, impact:non-functional, type:bug

#529 SpellCheck: force no color codes
  .pytool/Plugin/SpellCheck/SpellCheck.py
Labels: impact:non-functional

#531 [CHERRY-PICK] [202208] SpellCheck: force no color codes
  .pytool/Plugin/SpellCheck/SpellCheck.py
Labels: impact:non-functional

#513 LineEndingsCheck: improve performance
  .pytool/Plugin/LineEndingCheck/LineEndingCheck.py
  .pytool/Plugin/LineEndingCheck/Readme.md
  BaseTools/BaseTools.ci.yaml
Labels: impact:breaking-change, impact:non-functional

#537 Fix Python logging.warn() deprecation warnings
  .pytool/Plugin/DebugMacroCheck/DebugMacroCheck.py
  .pytool/Plugin/ImageValidation/ImageValidation.py
  .pytool/Plugin/LineEndingCheck/LineEndingCheck.py
  .pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py
  PolicyServicePkg/Plugins/UpdatePolicyHdr/UpdatePolicyHdr.py
Labels: language:python, impact:non-functional

#534 DXE and SMM core performance lib codeql changes.
  MdeModulePkg/Library/DxeCorePerformanceLib/DxeCorePerformanceLib.c
  MdeModulePkg/Library/SmmCorePerformanceLib/SmmCorePerformanceLib.c
Labels: impact:non-functional

#539 Resolve mws deprecations
  .pytool/Plugin/CodeQL/CodeQlAnalyzePlugin.py
  .pytool/Plugin/CodeQL/CodeQlBuildPlugin.py
  .pytool/Plugin/DebugMacroCheck/BuildPlugin/DebugMacroCheckBuildPlugin.py
  .pytool/Plugin/ImageValidation/ImageValidation.py
  BaseTools/Plugin/BmpCheck/BmpCheckPlugin.py
  BaseTools/Plugin/FdSizeReport/FdSizeReportGenerator.py
  BaseTools/Plugin/OverrideValidation/OverrideValidation.py
  PolicyServicePkg/Plugins/UpdatePolicyHdr/UpdatePolicyHdr.py
Labels: language:python, impact:breaking-change, impact:non-functional

#540 LineEndingCheck: bugfix: Fails if not run from workspace root
  .pytool/Plugin/LineEndingCheck/LineEndingCheck.py
Labels: impact:non-functional

#541 .pytool/Plugin/RustHostUnitTestPlugin: Ensure strings in ignore list
  .pytool/Plugin/RustHostUnitTestPlugin/RustHostUnitTestPlugin.py
Labels: type:bug

#545 .pytool/Plugin/RustHostUnitTestPlugin: Handle no coverage results
  .pytool/Plugin/RustHostUnitTestPlugin/RustHostUnitTestPlugin.py
Labels: type:bug
