Repository microsoft/mu_basecore, pull requests merged in 2023-05, with the labels that each got.

#384 MdeModulePkg/Core: Reduce stack cookie value verbosity
  MdeModulePkg/Core/Dxe/Image/Image.c
  MdeModulePkg/Core/PiSmmCore/Dispatcher.c
Labels: impact:non-functional, semver:patch

#352 Converge on 4k Section Alignment for AARCH64 Builds
  BaseTools/Conf/tools_def.template
Labels: impact:non-functional

#388 Remove the ARM GCC compiler extdeps to use container GCC
  BaseTools/Bin/gcc_aarch64_linux_ext_dep.yaml
  BaseTools/Bin/gcc_arm_linux_ext_dep.yaml
Labels: impact:breaking-change

#389 Fixing bug with newer versions of markdownlint
  .pytool/Plugin/MarkdownLintCheck/MarkdownLintCheck.py
Labels: impact:non-functional

#391 Revert "Converge on 4k Section Alignment for AARCH64 Builds (#352)"
  BaseTools/Conf/tools_def.template
Labels: impact:non-functional

#396 Add basic wrappers to the Policy Library
  PolicyServicePkg/Include/Library/PolicyLib.h
  PolicyServicePkg/Library/DxePolicyLib/DxePolicy.c
  PolicyServicePkg/Library/MmPolicyLib/MmPolicy.c
  PolicyServicePkg/Library/PeiPolicyLib/PeiPolicy.c
  PolicyServicePkg/Library/PolicyLibCommon.c
  PolicyServicePkg/PolicyService/DxeMm/PolicyCommon.c
  PolicyServicePkg/PolicyService/DxeMm/PolicyCommon.h
  PolicyServicePkg/PolicyService/DxeMm/PolicyDxe.c
  PolicyServicePkg/PolicyService/DxeMm/PolicyMm.c
  PolicyServicePkg/PolicyServicePkg.dec
  PolicyServicePkg/Samples/PolicyDefinitions/PolicyDataStructGFX.h
  PolicyServicePkg/Test/UnitTest/PolicyTest/PolicyLibTestCommon.c
  PolicyServicePkg/Tools/GenCfgData.py
Labels: language:python, impact:testing

#399 update cargo make build flags
  BaseTools/Conf/tools_def.template
Labels: impact:non-functional

#385 Create Github Workflow to publish basetools on release
  .github/workflows/release-basetools.yml
  BaseTools/Edk2ToolsBuild.py
Labels: language:python, impact:non-functional

#400 Additional CodeQL Fixes
  CodeQlFilters.yml
  NetworkPkg/Ip6Dxe/Ip6Mld.c
  NetworkPkg/Ip6Dxe/Ip6Nd.c
  ShellPkg/Application/Shell/ShellParametersProtocol.c
  ShellPkg/Library/UefiShellDriver1CommandsLib/OpenInfo.c
  UnitTestFrameworkPkg/Library/UnitTestPersistenceLibSimpleFileSystem/UnitTestPersistenceLibSimpleFileSystem.c
Labels: impact:security

#410 Stop USB enumeration in case a malformed descriptor is found
  MdeModulePkg/Bus/Usb/UsbBusDxe/UsbDesc.c
Labels: type:bug

#412 [CHERRY-PICK] Stop USB enumeration in case a malformed descriptor is found (#410)
  MdeModulePkg/Bus/Usb/UsbBusDxe/UsbDesc.c
Labels: impact:non-functional

#417 REBASE: Re-remove the codeql workflow
  .github/codeql/codeql-config.yml
  .github/codeql/edk2.qls
  .github/workflows/codeql-analysis.yml
Labels: impact:non-functional

#420 Add support for IAD-style USB input devices in ConPlatform
  MdeModulePkg/Universal/Console/ConPlatformDxe/ConPlatform.c
Labels: type:enhancement

#419 Enable crypto binaries for 202302
  CryptoPkg/Driver/Bin/BaseCryptoDriver_ext_dep.json
Labels: type:enhancement, impact:security

#418 Update basetools for 202302 using the github release.
  BaseTools/Bin/basetoolsbin_ext_dep.yaml
Labels: impact:non-functional

#424 CodeQL Fix: Add NULL Check to Generated Filename in UnitTestPersistLibSfs
  UnitTestFrameworkPkg/Library/UnitTestPersistenceLibSimpleFileSystem/UnitTestPersistenceLibSimpleFileSystem.c
Labels: impact:security, impact:non-functional
