Repository microsoft/mu_basecore, pull requests merged in 2023-01, with the labels that each got.

#219 HostUnitTestCompilerPlugin: enable single module build test execution
  .pytool/Plugin/HostUnitTestCompilerPlugin/HostUnitTestCompilerPlugin.py
  .pytool/Plugin/HostUnitTestCompilerPlugin/Readme.md
Labels: impact:non-functional, type:documentation, type:bug

#208 Add Readme Section on Memory Protection Special Regions
  Docs/feature_memory_protection.md
Labels: impact:non-functional, type:documentation

#218 Update the FillMemoryMap() Routine to Calculate the Required Buffer Size Before Allocation
  MdeModulePkg/Core/Dxe/Misc/MemoryProtectionSupport.c
Labels: impact:non-functional

#211 Set MMIO NX Based on Memory Protection Policy
  MdeModulePkg/Bus/Pci/PciHostBridgeDxe/PciHostBridge.c
  MdeModulePkg/Bus/Pci/PciHostBridgeDxe/PciHostBridgeDxe.inf
Labels: impact:security

#216 Add CpuMpDebugProtocol for Debug Reporting AP Stack Buffers
  UefiCpuPkg/CpuDxe/CpuMp.c
  UefiCpuPkg/Include/Library/MpInitLib.h
  UefiCpuPkg/Include/Protocol/CpuMpDebug.h
  UefiCpuPkg/Library/MpInitLib/DxeMpInitLib.inf
  UefiCpuPkg/Library/MpInitLib/DxeMpLib.c
  UefiCpuPkg/Library/MpInitLib/PeiMpLib.c
  UefiCpuPkg/UefiCpuPkg.dec
Labels: impact:non-functional

#225 Restore BSP Exception Stack Initialization
  MdeModulePkg/Core/Dxe/DxeMain/DxeMain.c
Labels: impact:security, type:bug

#227 Updated readme to include changes of note that happened with the 202208 transition.
  ReadMe.rst
Labels: impact:non-functional, type:documentation

#238 Bugfix: Move Variables into Memory Map Fill Loop to Handle Side Effects
  MdeModulePkg/Core/Dxe/Misc/MemoryProtectionSupport.c
Labels: impact:non-functional, type:bug

#237 Update edk2-pytool-library
  BaseTools/Plugin/WindowsVsToolChain/WindowsVsToolChain.py
  pip-requirements.txt
Labels: language:python, impact:breaking-change, impact:non-functional
