Repository microsoft/mu_basecore, pull requests merged in 2023-04, with the labels that each got.

#346 SetupBrowserDxe: Initialize the variable 'BrowserStorage'
  MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c
Labels: impact:non-functional

#340 python: resolve parser deprecation warnings
  .pytool/Plugin/CompilerPlugin/CompilerPlugin.py
  .pytool/Plugin/DependencyCheck/DependencyCheck.py
  .pytool/Plugin/DscCompleteCheck/DscCompleteCheck.py
  .pytool/Plugin/HostUnitTestCompilerPlugin/HostUnitTestCompilerPlugin.py
  .pytool/Plugin/HostUnitTestDscCompleteCheck/HostUnitTestDscCompleteCheck.py
  .pytool/Plugin/ImageValidation/ImageValidation.py
  .pytool/Plugin/LibraryClassCheck/LibraryClassCheck.py
  BaseTools/Plugin/BmpCheck/BmpCheckPlugin.py
  BaseTools/Plugin/OverrideValidation/OverrideValidation.py
Labels: language:python, impact:non-functional, complexity:easy

#357 Fix MdeModulePkg host test
  MdeModulePkg/Test/MdeModulePkgHostTest.dsc
Labels: impact:non-functional, impact:testing

#347 Infinite boot retries
  MdeModulePkg/MdeModulePkg.dec
  MdeModulePkg/Universal/BdsDxe/BdsDxe.inf
  MdeModulePkg/Universal/BdsDxe/BdsEntry.c
Labels: type:enhancement, type:feature-request

#364 Plugin/CodeQL: Linux fixes
  .pytool/Plugin/CodeQL/CodeQlBuildPlugin.py
Labels: impact:non-functional

#358 Additional CodeQL Fixes
  MdeModulePkg/Core/Dxe/Mem/Pool.c
  NetworkPkg/Ip6Dxe/Ip6Input.c
  NetworkPkg/Ip6Dxe/Ip6Mld.c
  NetworkPkg/Ip6Dxe/Ip6Nd.c
  ShellPkg/Application/Shell/ShellManParser.c
  ShellPkg/Library/UefiShellBcfgCommandLib/UefiShellBcfgCommandLib.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/Edit/MainTextEditor.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/HexEdit/MainHexEditor.c
  ShellPkg/Library/UefiShellDriver1CommandsLib/DrvCfg.c
  ShellPkg/Library/UefiShellDriver1CommandsLib/OpenInfo.c
  ShellPkg/Library/UefiShellDriver1CommandsLib/Unload.c
  UnitTestFrameworkPkg/Library/UnitTestPersistenceLibSimpleFileSystem/UnitTestPersistenceLibSimpleFileSystem.c
Labels: impact:security

#367 Handling the continue cases for BDS retry
  MdeModulePkg/Universal/BdsDxe/BdsEntry.c
Labels: type:bug

#370 Removing BASECORE overrides for unit test include file
  MdeModulePkg/Test/MdeModulePkgHostTest.dsc
  UnitTestFrameworkPkg/UnitTestFrameworkPkgHost.dsc.inc
Labels: impact:testing

#362 Adding base tool build for Linux ARM
  .azurepipelines/BaseTools-Build-For-Publication.yml
  BaseTools/Edk2ToolsBuild.py
  BaseTools/Source/C/DevicePath/GNUmakefile
  BaseTools/Source/C/GenFv/GNUmakefile
  BaseTools/Source/C/GenFv/GenFvInternalLib.c
  BaseTools/Source/C/GenFw/GNUmakefile
  BaseTools/Source/C/GenSec/GNUmakefile
  BaseTools/Source/C/Makefiles/header.makefile
Labels: type:enhancement, language:python

#376 Add Windows ARM 64-bit base tools
  .azurepipelines/BaseTools-Build-For-Publication.yml
  BaseTools/.gitignore
  BaseTools/Edk2ToolsBuild.py
  BaseTools/Source/C/Include/AArch64/ProcessorBind.h
  BaseTools/Source/C/Makefiles/ms.common
Labels: type:enhancement, language:python, type:feature-request

#374 Mark NonDiscoverablePciDeviceIo Memory XP By Default
  MdeModulePkg/Bus/Pci/NonDiscoverablePciDeviceDxe/NonDiscoverablePciDeviceIo.c
Labels: impact:security

#365 Updated Base Crypto Version to 2022.8.6
  CryptoPkg/Driver/Bin/BaseCryptoDriver_ext_dep.json
Labels: impact:security, impact:non-functional

#378 Revert #168. Move changes into Terminal driver's Terminal ConIn.
  MdeModulePkg/Bus/Pci/PciSioSerialDxe/SerialIo.c
  MdeModulePkg/Universal/Console/TerminalDxe/TerminalConIn.c
Labels: type:enhancement, complexity:easy

#375 [CHERRY-PICK] BaseTools/Plugin: Clarify code coverage failure message
  BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
Labels: type:enhancement, language:python, impact:non-functional, type:documentation

#372 Updated Crypto Tests
  CryptoPkg/CryptoPkg.dsc
  CryptoPkg/Test/Crypto.pcd.ALL.inc.dsc
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/AuthenticodeTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/BaseCryptLibUnitTestApp.inf
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/BlockCipherTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/DhTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/HashTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/HmacTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/OaepEncryptTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/ParallelhashTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/Pkcs5Pbkdf2Tests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/Pkcs7EkuTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/RandTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/RsaPkcs7Tests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/RsaPssTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/RsaTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TSTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestBaseCryptLibHost.inf
Labels: impact:non-functional, impact:testing

#379 Updating all binary releases
  .pytool/Plugin/UncrustifyCheck/uncrustify_ext_dep.yaml
  BaseTools/Bin/basetoolsbin_ext_dep.yaml
  BaseTools/Bin/iasl_ext_dep.yaml
  BaseTools/Bin/nasm_ext_dep.yaml
Labels: type:enhancement

#381 Edk2ToolsBuild.py: set arch to host arch if not specified on linux
  BaseTools/Edk2ToolsBuild.py
Labels: language:python, impact:non-functional

#382 Fix dmpstore regressed during CodeQL changes
  ShellPkg/Library/UefiShellDebug1CommandsLib/DmpStore.c
Labels: type:bug
