Repository microsoft/mu_basecore, pull requests merged in 2023-03, with the labels that each got.

#290 MdePkg/BaseMemoryLib: Prevent VS2022 (17.5) linker failure
  MdePkg/Library/BaseMemoryLib/MemLibGeneric.c
Labels: impact:non-functional

#288 IndustryStandard\IpmiNetFnSensorEvent.h: Added SetSensorThreshold and GetSensorThreshold commands
  MdePkg/Include/IndustryStandard/IpmiNetFnSensorEvent.h
Labels: impact:non-functional

#295 CodeQlFilters.yml: Filter updates
  CodeQlFilters.yml
Labels: impact:non-functional

#286 Remove MemoryAttributeProtocolFuncTestApp
  MdePkg/MdePkg.dsc
  MdePkg/Test/ShellTest/MemoryAttributeProtocolFuncTestApp/MemoryAttributeProtocolFuncTestApp.c
  MdePkg/Test/ShellTest/MemoryAttributeProtocolFuncTestApp/MemoryAttributeProtocolFuncTestApp.h
  MdePkg/Test/ShellTest/MemoryAttributeProtocolFuncTestApp/MemoryAttributeProtocolFuncTestApp.inf
  MdePkg/Test/ShellTest/MemoryAttributeProtocolFuncTestApp/PageSplitTest.c
  MdePkg/Test/ShellTest/MemoryAttributeProtocolFuncTestApp/Readme.md
  MdePkg/Test/ShellTest/MemoryAttributeProtocolFuncTestApp/X64/PageSplitTest.c
Labels: impact:non-functional

#296 NetworkPkg\Ip6Dxe and MdeModulePkg\Universal\SetupBrowserDxe: Fix Previous CodeQL fix
  MdeModulePkg/Universal/SetupBrowserDxe/Setup.c
  NetworkPkg/Ip6Dxe/Ip6If.c
Labels: impact:non-functional

#299 LineEndingCheck: Fix bare except
  .pytool/Plugin/LineEndingCheck/LineEndingCheck.py
Labels: language:python, impact:non-functional, complexity:easy, semver:patch

#303 MicrocodeMeasurementDxe debug string correction
  UefiCpuPkg/MicrocodeMeasurementDxe/MicrocodeMeasurementDxe.c
Labels: impact:security, impact:non-functional, complexity:easy, type:bug

#309 Update CodeQL CLI from 2.11.2 to 2.12.4
  .pytool/Plugin/CodeQL/codeqlcli_ext_dep.yaml
  .pytool/Plugin/CodeQL/codeqlcli_linux_ext_dep.yaml
  .pytool/Plugin/CodeQL/codeqlcli_windows_ext_dep.yaml
Labels: impact:non-functional

#316 UnitTestFrameworkPkg: More CodeQL fixes
  UnitTestFrameworkPkg/Library/UnitTestPersistenceLibSimpleFileSystem/UnitTestPersistenceLibSimpleFileSystem.c
Labels: impact:security

#317 NetworkPkg: More CodeQL fixes
  NetworkPkg/HttpBootDxe/HttpBootConfig.c
  NetworkPkg/Ip4Dxe/Ip4Config2Nv.c
  NetworkPkg/Ip6Dxe/Ip6ConfigNv.c
  NetworkPkg/Ip6Dxe/Ip6Output.c
  NetworkPkg/Library/DxeHttpIoLib/DxeHttpIoLib.c
  NetworkPkg/TcpDxe/TcpOutput.c
  NetworkPkg/VlanConfigDxe/VlanConfigImpl.c
Labels: impact:security

#319 MdeModulePkg: More CodeQL fixes
  MdeModulePkg/Bus/Pci/PciBusDxe/PciResourceSupport.c
  MdeModulePkg/Bus/Usb/UsbMouseAbsolutePointerDxe/UsbMouseAbsolutePointer.c
  MdeModulePkg/Core/Dxe/Dispatcher/Dispatcher.c
  MdeModulePkg/Core/Dxe/Image/Image.c
  MdeModulePkg/Core/Dxe/Misc/MemoryAttributesTable.c
  MdeModulePkg/Core/Dxe/Misc/MemoryProtection.c
  MdeModulePkg/Core/Dxe/SectionExtraction/CoreSectionExtraction.c
  MdeModulePkg/Library/DxeCapsuleLibFmp/CapsuleOnDisk.c
  MdeModulePkg/Library/UefiBootManagerLib/BmBootDescription.c
  MdeModulePkg/Library/UefiBootManagerLib/BmDriverHealth.c
  MdeModulePkg/Library/UefiBootManagerLib/BmHotkey.c
  MdeModulePkg/Library/UefiBootManagerLib/BmLoadOption.c
  MdeModulePkg/Library/UefiHiiLib/HiiLib.c
  MdeModulePkg/Library/UefiHiiLib/UefiHiiLib.inf
  MdeModulePkg/Library/UefiSortLib/UefiSortLib.c
  MdeModulePkg/Universal/Acpi/AcpiTableDxe/AcpiTable.c
  MdeModulePkg/Universal/Acpi/AcpiTableDxe/AmlNamespace.c
  MdeModulePkg/Universal/Console/GraphicsConsoleDxe/GraphicsConsole.c
  MdeModulePkg/Universal/FvSimpleFileSystemDxe/FvSimpleFileSystemEntryPoint.c
  MdeModulePkg/Universal/HiiDatabaseDxe/ConfigKeywordHandler.c
  MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c
  MdeModulePkg/Universal/HiiDatabaseDxe/Font.c
  MdeModulePkg/Universal/HiiDatabaseDxe/HiiDatabaseDxe.inf
  MdeModulePkg/Universal/HiiDatabaseDxe/String.c
  MdeModulePkg/Universal/PCD/Dxe/Pcd.c
  MdeModulePkg/Universal/PCD/Dxe/Service.c
  MdeModulePkg/Universal/SetupBrowserDxe/Expression.c
  MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c
  MdeModulePkg/Universal/SetupBrowserDxe/Presentation.c
  MdeModulePkg/Universal/SetupBrowserDxe/Setup.c
Labels: impact:security

#318 MdePkg: More CodeQL fixes
  MdePkg/Library/UefiFileHandleLib/UefiFileHandleLib.c
  MdePkg/Library/UefiLib/Console.c
  MdePkg/Library/UefiLib/UefiLibPrint.c
Labels: impact:security

#321 ShellPkg: More CodeQL fixes
  ShellPkg/Application/Shell/FileHandleWrappers.c
  ShellPkg/Application/Shell/Shell.c
  ShellPkg/Application/Shell/ShellParametersProtocol.c
  ShellPkg/Application/Shell/ShellProtocol.c
  ShellPkg/Library/UefiHandleParsingLib/UefiHandleParsingLib.c
  ShellPkg/Library/UefiShellBcfgCommandLib/UefiShellBcfgCommandLib.c
  ShellPkg/Library/UefiShellCommandLib/ConsistMapping.c
  ShellPkg/Library/UefiShellCommandLib/UefiShellCommandLib.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/DmpStore.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/EditMenuBar.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/LoadPciRom.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/MemMap.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/SetVar.c
  ShellPkg/Library/UefiShellDriver1CommandsLib/DevTree.c
  ShellPkg/Library/UefiShellDriver1CommandsLib/Devices.c
  ShellPkg/Library/UefiShellDriver1CommandsLib/Dh.c
  ShellPkg/Library/UefiShellDriver1CommandsLib/Drivers.c
  ShellPkg/Library/UefiShellDriver1CommandsLib/DrvCfg.c
  ShellPkg/Library/UefiShellDriver1CommandsLib/DrvDiag.c
  ShellPkg/Library/UefiShellLevel1CommandsLib/For.c
  ShellPkg/Library/UefiShellLevel2CommandsLib/Cp.c
  ShellPkg/Library/UefiShellLevel2CommandsLib/Ls.c
  ShellPkg/Library/UefiShellLevel2CommandsLib/Vol.c
  ShellPkg/Library/UefiShellLevel3CommandsLib/Help.c
  ShellPkg/Library/UefiShellLib/UefiShellLib.c
  ShellPkg/Library/UefiShellNetwork2CommandsLib/Ifconfig6.c
  ShellPkg/ShellPkg.dsc
Labels: impact:security

#323 Adding support of building BaseTool for Windows ARM
  .azurepipelines/BaseTools-Build-For-Publication.yml
  BaseTools/Edk2ToolsBuild.py
  BaseTools/NugetPublishing/Mu-Basetools.config.json
  BaseTools/Plugin/WindowsVsToolChain/WindowsVsToolChain.py
  BaseTools/Source/C/GenFw/GenFw.c
  BaseTools/Source/C/Include/Arm/ProcessorBind.h
  BaseTools/Source/C/Include/IndustryStandard/PeImage.h
  BaseTools/Source/C/Makefile
  BaseTools/Source/C/Makefiles/ms.common
Labels: language:python

#325 Update iasl_ext_dep.yaml
  BaseTools/Bin/iasl_ext_dep.yaml
Labels: impact:non-functional

#320 CryptoPkg: More CodeQL fixes
  CryptoPkg/Library/BaseCryptLib/Pk/CryptAuthenticode.c
  CryptoPkg/Library/BaseCryptLib/Pk/CryptDh.c
  CryptoPkg/Library/BaseCryptLib/Pk/CryptTs.c
  CryptoPkg/Library/BaseCryptLib/Pk/CryptX509.c
Labels: impact:security

#329 bugfix: Update iasl_ext_dep.yaml
  BaseTools/Bin/iasl_ext_dep.yaml
Labels: impact:non-functional, type:bug

#322 Update CodeQlFilters
  CodeQlFilters.yml
Labels: impact:security

#330 Update nasm_ext_dep.yaml
  BaseTools/Bin/nasm_ext_dep.yaml
Labels: type:dependencies, impact:non-functional

#333 Introduce code coverage job for matrix build
  .azurepipelines/Matrix-Build-Job.yml
  BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
Labels: language:python, impact:non-functional
