Repository microsoft/mu_basecore, pull requests merged in 2023-10, with the labels that each got.

#583 RustHostUnitTestPlugin: Skip plugin when package has no rust crates
  .pytool/Plugin/RustHostUnitTestPlugin/RustHostUnitTestPlugin.py
Labels: impact:non-functional

#586 Remove datetime.utcnow() support from OverrideValidation.py
  BaseTools/Plugin/FlattenPdbs/FlattenPdbs.py
  BaseTools/Plugin/OverrideValidation/OverrideValidation.py
Labels: language:python, impact:breaking-change, impact:non-functional

#587 BaseTools/Conf: Update file versions for Rust changes
  BaseTools/Conf/build_rule.template
  BaseTools/Conf/tools_def.template
Labels: impact:non-functional, type:bug

#509 Add CI Plugin: NestedPackageCheck
  .pytool/Plugin/NestedPackageCheck/NestedPackageCheck.py
  .pytool/Plugin/NestedPackageCheck/NestedPackageCheck_plug_in.yaml
  .pytool/Plugin/NestedPackageCheck/Readme.md
Labels: impact:non-functional

#582 Add a Panic Library to MdePkg
  MdePkg/Include/Library/PanicLib.h
  MdePkg/Library/BasePanicLibNull/BasePanicLibNull.c
  MdePkg/Library/BasePanicLibNull/BasePanicLibNull.inf
  MdePkg/Library/BasePanicLibSerialPort/BasePanicLibSerialPort.c
  MdePkg/Library/BasePanicLibSerialPort/BasePanicLibSerialPort.inf
  MdePkg/MdePkg.dec
  MdePkg/MdePkg.dsc
Labels: type:design-change, type:feature-request

#595 MdeModulePkg/MemoryTypeInfoSecVarCheckLib: Elaborate on expected mem types
  MdeModulePkg/Library/MemoryTypeInfoSecVarCheckLib/MemoryTypeInfoSecVarCheckLib.c
Labels: impact:non-functional, type:documentation

#597 [PolicyServicePkg] Adding MemoryAllocationLib to library classes that rely on it
  PolicyServicePkg/Library/DxePolicyLib/DxePolicyLib.inf
  PolicyServicePkg/Library/MmPolicyLib/MmPolicyLib.inf
  PolicyServicePkg/Library/PeiPolicyLib/PeiPolicyLib.inf
Labels: impact:non-functional

#561 MdeModulePkg and UefiCpuPkg CodeQL Fixes
  MdeModulePkg/MdeModulePkg.dsc
  MdeModulePkg/Universal/PCD/Pei/Pcd.c
  MdeModulePkg/Universal/PCD/Pei/Service.c
  MdeModulePkg/Universal/ResetSystemPei/ResetSystem.c
  MdeModulePkg/Universal/ResetSystemPei/ResetSystem.h
  MdeModulePkg/Universal/ResetSystemPei/ResetSystemPei.inf
  UefiCpuPkg/CpuDxe/CpuDxe.inf
  UefiCpuPkg/CpuDxe/CpuMp.c
  UefiCpuPkg/CpuDxe/CpuPageTable.c
  UefiCpuPkg/CpuMpPei/CpuMpPei.c
  UefiCpuPkg/CpuMpPei/CpuMpPei.h
  UefiCpuPkg/CpuMpPei/CpuMpPei.inf
  UefiCpuPkg/CpuMpPei/CpuPaging.c
  UefiCpuPkg/Library/MpInitLib/DxeMpLib.c
  UefiCpuPkg/Library/MpInitLib/MpLib.c
  UefiCpuPkg/Library/MpInitLib/PeiMpLib.c
  UefiCpuPkg/UefiCpuPkg.dsc
Labels: impact:non-functional

#598 EsrtFmp CodeQL Fix
  MdeModulePkg/Universal/EsrtFmpDxe/EsrtFmp.c
Labels: impact:security

#600 BaseTools/Plugin: Add Rust Environment Check build plugin
  BaseTools/Plugin/RustEnvironmentCheck/RustEnvironmentCheck.py
  BaseTools/Plugin/RustEnvironmentCheck/RustEnvironmentCheck_plug_in.yaml
Labels: language:python, type:feature-request

#602 BaseTools/Plugin: Add tool exclusion to RustEnvironmentCheck
  BaseTools/Plugin/RustEnvironmentCheck/RustEnvironmentCheck.py
Labels: type:enhancement, language:python, impact:non-functional, type:documentation

#604 BinToPcd.py: Update regex strings to use raw strings
  BaseTools/Scripts/BinToPcd.py
Labels: language:python, impact:non-functional

#605 Fixing incorrect monotonic counter comment in INF file
  MdeModulePkg/Universal/MonotonicCounterRuntimeDxe/MonotonicCounterRuntimeDxe.inf
Labels: impact:non-functional
