Repository microsoft/mu_basecore, pull requests merged in 2023-07, with the labels that each got.

#481 CI: Add Rust Host Unit Test CI check
  .pytool/Plugin/RustHostUnitTestPlugin/Readme.md
  .pytool/Plugin/RustHostUnitTestPlugin/RustHostUnitTestPlugin.py
  .pytool/Plugin/RustHostUnitTestPlugin/RustHostUnitTest_plug_in.yaml
  .pytool/Plugin/RustPackageHelper/RustPackageHelper.py
  .pytool/Plugin/RustPackageHelper/RustPackageHelper_plug_in.yaml
  Docs/rust_build.md
  Makefile.toml
  pip-requirements.txt
Labels: impact:non-functional, type:documentation

#484 .github/release-draft.yml: Use Mu DevOps 5.0.4
  .github/workflows/release-draft.yml
Labels: type:dependencies, impact:non-functional

#392 Refactoring infinite boot option retries
  MdeModulePkg/Universal/BdsDxe/BdsEntry.c
Labels: complexity:easy, type:bug

#487 [CHERRY-PICK]: MdeModulePkg/BdsDxe/BaseEntry.c Refactoring infinite boot option retries (#392)
  MdeModulePkg/Universal/BdsDxe/BdsEntry.c
Labels: impact:non-functional

#488 Fix CodeQL errors
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/UnitTestMain.c
  MdeModulePkg/Core/Pei/Ppi/Ppi.c
  MdeModulePkg/Core/PiSmmCore/PiSmmIpl.c
  MdeModulePkg/Universal/SetupBrowserDxe/Expression.c
  NetworkPkg/Ip4Dxe/Ip4Input.c
  NetworkPkg/Ip6Dxe/Ip6ConfigImpl.c
  NetworkPkg/Ip6Dxe/Ip6Input.c
  NetworkPkg/Ip6Dxe/Ip6Nd.c
  NetworkPkg/Ip6Dxe/Ip6Output.c
  NetworkPkg/Library/DxeNetLib/NetBuffer.c
  NetworkPkg/TcpDxe/TcpOption.c
  NetworkPkg/TcpDxe/TcpOutput.c
  UefiCpuPkg/PiSmmCpuDxeSmm/CpuS3.c
  UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c
  UnitTestFrameworkPkg/Library/UnitTestPersistenceLibSimpleFileSystem/UnitTestPersistenceLibSimpleFileSystem.c
Labels: impact:security, impact:non-functional

#490 Fix CodeQL errors
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/UnitTestMain.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/X509Tests.c
  MdeModulePkg/Core/Pei/Ppi/Ppi.c
  MdeModulePkg/Core/PiSmmCore/PiSmmIpl.c
  MdeModulePkg/Universal/SetupBrowserDxe/Expression.c
  NetworkPkg/Ip4Dxe/Ip4Input.c
  NetworkPkg/Ip6Dxe/Ip6ConfigImpl.c
  NetworkPkg/Ip6Dxe/Ip6Input.c
  NetworkPkg/Ip6Dxe/Ip6Nd.c
  NetworkPkg/Ip6Dxe/Ip6Output.c
  NetworkPkg/Library/DxeNetLib/NetBuffer.c
  NetworkPkg/TcpDxe/TcpOption.c
  NetworkPkg/TcpDxe/TcpOutput.c
  UefiCpuPkg/CpuMpPei/CpuMpPei.c
  UefiCpuPkg/PiSmmCpuDxeSmm/CpuS3.c
  UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c
  UnitTestFrameworkPkg/Library/UnitTestPersistenceLibSimpleFileSystem/UnitTestPersistenceLibSimpleFileSystem.c
Labels: impact:security, impact:non-functional

#492 CryptEc.c CodeQL Fix
  CryptoPkg/Library/BaseCryptLib/Pk/CryptEc.c
Labels: impact:security

#499 BaseTools: Detect library class mismatch [REBASE&FF]
  BaseTools/Source/Python/AutoGen/AutoGenWorker.py
  BaseTools/Source/Python/Common/GlobalData.py
  BaseTools/Source/Python/Workspace/DscBuildData.py
  BaseTools/Source/Python/Workspace/WorkspaceCommon.py
Labels: language:python, impact:non-functional

#500 Update IORT SMMUv3 IORT node flags for HTTU to include dirty state support
  MdePkg/Include/IndustryStandard/IoRemappingTable.h
Labels: impact:non-functional
