Repository microsoft/mu_basecore, pull requests merged in 2023-09, with the labels that each got.

#552 CodeQlFilters.yml: Glob file patterns in nested directories
  CodeQlFilters.yml
Labels: type:enhancement, impact:non-functional, type:bug

#554 MdeModulePkg/VariablePolicyLib: Use wildcard character constant
  MdeModulePkg/Library/VariablePolicyLib/VariablePolicyLib.c
  MdeModulePkg/Library/VariablePolicyLib/VariablePolicyUnitTest/VariablePolicyUnitTest.c
Labels: impact:non-functional, impact:testing

#548 Drop Rust Docs for Move to Mu Documentation
  Docs/rust_build.md
  Docs/rust_documentation_conventions.md
  RepoDetails.md
Labels: impact:non-functional, type:documentation

#556 PolicyServicePkg/PolicyLib.h: Add missing include guard
  PolicyServicePkg/Test/UnitTest/PolicyTest/PolicyTest.h
Labels: impact:non-functional, type:bug

#566 Fix Redefined Callback
  PolicyServicePkg/Library/DxePolicyLib/DxePolicy.c
Labels: impact:non-functional

#564 Added Ipmi Threshold sensor APIs and their NULL implementation
  MdeModulePkg/Include/Library/IpmiCommandLib.h
  MdeModulePkg/Library/BaseIpmiCommandLibNull/BaseIpmiCommandLibNull.inf
  MdeModulePkg/Library/BaseIpmiCommandLibNull/IpmiCommandLibNetFnSensor.c
Labels: impact:non-functional

#568 Update CodeQL CLI from v2.12.4 to v2.14.5
  .pytool/Plugin/CodeQL/codeqlcli_linux_ext_dep.yaml
  .pytool/Plugin/CodeQL/codeqlcli_windows_ext_dep.yaml
Labels: impact:non-functional

#558 Don't Lock Variable Policy if Device is in Unit Test Mode
  MdeModulePkg/MdeModulePkg.dsc
  MdeModulePkg/Universal/Variable/RuntimeDxe/VariablePolicyLockingCommon.c
  MdeModulePkg/Universal/Variable/RuntimeDxe/VariableRuntimeDxe.inf
  MdeModulePkg/Universal/Variable/RuntimeDxe/VariableSmmRuntimeDxe.inf
Labels: impact:security

#567 [CHERRY-PICK]MdeModulePkg: HeapGuard: Don't Assume Pool Head Allocated In First Page
  MdeModulePkg/Core/Dxe/Mem/HeapGuard.c
  MdeModulePkg/Core/Dxe/Mem/HeapGuard.h
  MdeModulePkg/Core/Dxe/Mem/Pool.c
Labels: impact:non-functional

#572 Change assert to not fire when intentionally disabling PCI enumeration
  MdeModulePkg/Bus/Pci/PciBusDxe/PciDeviceSupport.c
Labels: impact:non-functional

#578 .pytool/Plugin: Improve Rust support
  .pytool/Plugin/RustHostUnitTestPlugin/RustHostUnitTestPlugin.py
  .pytool/Plugin/RustPackageHelper/RustPackageHelper.py
Labels: type:enhancement, impact:non-functional

#579 Create Google mock for ReadOnlyVariable2
  MdePkg/Test/Mock/Include/GoogleTest/Ppi/MockReadOnlyVariable2.h
  MdePkg/Test/Mock/Library/GoogleTest/Ppi/MockReadOnlyVariable2.cpp
Labels: impact:non-functional

#580 .pytool/Plugin: Better Rust Support
  .pytool/Plugin/RustHostUnitTestPlugin/Readme.md
  .pytool/Plugin/RustHostUnitTestPlugin/RustHostUnitTestPlugin.py
  .pytool/Plugin/RustPackageHelper/RustPackageHelper.py
Labels: type:enhancement, impact:non-functional
