Repository microsoft/mu_basecore, pull requests merged in 2023-11, with the labels that each got.

#607 MdePkg/GoogleTest: Add GetTime() RT service mock interface
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiRuntimeServicesTableLib.h
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiRuntimeServicesTableLib/MockUefiRuntimeServicesTableLib.cpp
Labels: impact:non-functional

#611 BaseTools/Plugin/RustEnvironmentCheck: Add rust-src component check
  BaseTools/Plugin/RustEnvironmentCheck/RustEnvironmentCheck.py
Labels: type:enhancement, language:python, impact:non-functional

#614 .pytool/CISettings.py: Re-enable Code Coverage
  .azurepipelines/Ubuntu-GCC5.yml
  .azurepipelines/Windows-VS.yml
  .pytool/CISettings.py
  pip-requirements.txt
Labels: impact:non-functional

#599 MdeModulePkg/PciHostBridgeDxe: Add readback after final Cfg-Write
  MdeModulePkg/Bus/Pci/PciHostBridgeDxe/PciRootBridgeIo.c
Labels: type:design-change

#623 Add Gmock for UefiBootServicesTableLib
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiBootServicesTableLib.h
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiBootServicesTableLib/MockUefiBootServicesTableLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiBootServicesTableLib/MockUefiBootServicesTableLib.inf
Labels: impact:non-functional

#616 BaseTools: reformat HostBasedUnitTestRunner coverage results by inf
  .azurepipelines/Ubuntu-GCC5.yml
  .azurepipelines/Windows-VS.yml
  .github/codecov.yml
  .pytool/Plugin/HostUnitTestCompilerPlugin/HostUnitTestCompilerPlugin.py
  BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
  UnitTestFrameworkPkg/ReadMe.md
  pip-requirements.txt
Labels: language:python, impact:breaking-change, impact:non-functional

#619 Define GUID for boot manage policy to connect storage devices.
  MdePkg/Include/Protocol/BootManagerPolicy.h
  MdePkg/MdePkg.dec
Labels: impact:non-functional

#624 Add late initialization for Debug Agent
  MdeModulePkg/Core/Dxe/DxeMain/DxeMain.c
  MdeModulePkg/Include/Library/DebugAgentLib.h
Labels: impact:non-functional

#630 MdePkg/GoogleTest: Add HASH2 Protocol mock interface
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockHash2.h
  MdePkg/Test/Mock/Library/GoogleTest/Protocol/MockHash2.cpp
Labels: impact:non-functional

#634 Add Unaccepted Memory Type to Memory Protection Struct Definitions
  MdeModulePkg/Include/Guid/DxeMemoryProtectionSettings.h
  MdeModulePkg/Include/Guid/MmMemoryProtectionSettings.h
  MdeModulePkg/Library/MemoryProtectionHobLib/DxeMemoryProtectionHobLib.c
  MdeModulePkg/Library/MemoryProtectionHobLib/MmCommonMemoryProtectionHobLib.c
Labels: impact:breaking-change, impact:security

#637 Reduce GCC Stack Protection Level, Increment Tools Def Version
  BaseTools/Conf/tools_def.template
Labels: impact:security

#638 Bugfix: Fix Tools Def Version Number Incrementation
  BaseTools/Conf/tools_def.template
Labels: impact:non-functional

#640 Check for Clang and GCC Support When Defining NO_STACK_COOKIE
  MdePkg/Include/Base.h
Labels: impact:security
