Repository microsoft/mu_basecore, pull requests merged in 2023-12, with the labels that each got.

#613 [REBASE && FF] Update GetMemoryMapWithPopulatedAccessAttributes() to Defer Free/Allocate Calls, Improve Documentation
  MdeModulePkg/Core/Dxe/Misc/MemoryProtectionSupport.c
Labels: impact:security

#641 [CHERRY-PICK] MdePkg: Add ProcessorUpgradeSocket definitions from SMBIOS 3.7.0
  MdePkg/Include/IndustryStandard/SmBios.h
Labels: impact:non-functional

#636 Added codeql fixes to DxeCorePerformanceLib.c
  MdeModulePkg/Library/DxeCorePerformanceLib/DxeCorePerformanceLib.c
Labels: impact:non-functional

#649 Bugfix rust module incremental build support
  BaseTools/Conf/build_rule.template
  BaseTools/Source/Python/Common/Misc.py
  BaseTools/Source/Python/build/build.py
Labels: language:python, impact:non-functional

#647 Remake fdsizereportgenerator
  BaseTools/Plugin/FdSizeReport/FdReport_Template.html
  BaseTools/Plugin/FdSizeReport/FdSizeReportGenerator.py
Labels: language:python, impact:non-functional

#655 release-basetools.yml: Update for compatibility with v4 GitHub actions
  .github/workflows/release-basetools.yml
Labels: type:dependencies, impact:non-functional

#659 [CHERRY-PICK] BaseTools: Resolve regex syntax warnings
  BaseTools/Source/Python/AmlToC/AmlToC.py
  BaseTools/Source/Python/AutoGen/BuildEngine.py
  BaseTools/Source/Python/AutoGen/GenDepex.py
  BaseTools/Source/Python/AutoGen/GenMake.py
  BaseTools/Source/Python/AutoGen/IdfClassObject.py
  BaseTools/Source/Python/AutoGen/ModuleAutoGen.py
  BaseTools/Source/Python/AutoGen/StrGather.py
  BaseTools/Source/Python/AutoGen/WorkspaceAutoGen.py
  BaseTools/Source/Python/Common/Expression.py
  BaseTools/Source/Python/Common/GlobalData.py
  BaseTools/Source/Python/Common/Misc.py
  BaseTools/Source/Python/Common/ToolDefClassObject.py
  BaseTools/Source/Python/GenFds/FdfParser.py
  BaseTools/Source/Python/GenFds/GenFds.py
  BaseTools/Source/Python/GenPatchPcdTable/GenPatchPcdTable.py
  BaseTools/Source/Python/Trim/Trim.py
  BaseTools/Source/Python/Workspace/DscBuildData.py
  BaseTools/Source/Python/Workspace/MetaFileParser.py
Labels: language:python, impact:non-functional

#658 Update iasl ext dep to 20230628
  BaseTools/Bin/iasl_ext_dep.yaml
Labels: impact:non-functional

#609 Cherry pick and apply uncrustify changes
  .pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py
  .pytool/Plugin/UncrustifyCheck/uncrustify.cfg
  MdeModulePkg/Library/UefiSortLib/GoogleTest/UefiSortLibGoogleTest.cpp
  MdeModulePkg/Test/Mock/Include/GoogleTest/Library/MockPciHostBridgeLib.h
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockPciHostBridgeLib/MockPciHostBridgeLib.cpp
  MdePkg/Test/GoogleTest/Library/BaseSafeIntLib/SafeIntLibUintnIntnUnitTests32.cpp
  MdePkg/Test/GoogleTest/Library/BaseSafeIntLib/SafeIntLibUintnIntnUnitTests64.cpp
  MdePkg/Test/GoogleTest/Library/BaseSafeIntLib/TestBaseSafeIntLib.cpp
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockHobLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockPeiServicesLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiBootServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiRuntimeServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Ppi/MockReadOnlyVariable2.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockHash2.h
  MdePkg/Test/Mock/Library/GoogleTest/MockHobLib/MockHobLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockPeiServicesLib/MockPeiServicesLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiBootServicesTableLib/MockUefiBootServicesTableLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiLib/MockUefiLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiRuntimeServicesTableLib/MockUefiRuntimeServicesTableLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/Ppi/MockReadOnlyVariable2.cpp
  MdePkg/Test/Mock/Library/GoogleTest/Protocol/MockHash2.cpp
  UnitTestFrameworkPkg/Include/Library/GoogleTestLib.h
  UnitTestFrameworkPkg/Test/GoogleTest/Sample/SampleGoogleTest/SampleGoogleTest.cpp
Labels: impact:breaking-change, impact:non-functional

#654 Memory Protection: Add Missing Special Region Pattern Application in SeparateSpecialRegionsInMemoryMap()
  MdeModulePkg/Core/Dxe/Misc/MemoryProtectionSupport.c
Labels: impact:security, type:bug

#663 BaseTools: Fix raw strings containing valid escape characters
  BaseTools/Source/Python/AutoGen/GenMake.py
  BaseTools/Source/Python/Common/Misc.py
  BaseTools/Source/Python/Workspace/DscBuildData.py
Labels: language:python, impact:non-functional
