Repository microsoft/mu_basecore, pull requests merged in 2023-06, with the labels that each got.

#435 Remove passing print from Char Encoding Check Plugin
  .pytool/Plugin/CharEncodingCheck/CharEncodingCheck.py
Labels: impact:non-functional

#423 Integrate PrEval Policy 5
  CryptoPkg/CryptoPkg.ci.yaml
  MdeModulePkg/MdeModulePkg.ci.yaml
  MdePkg/MdePkg.ci.yaml
  NetworkPkg/NetworkPkg.ci.yaml
  PcAtChipsetPkg/PcAtChipsetPkg.ci.yaml
  PolicyServicePkg/PolicyServicePkg.ci.yaml
  ShellPkg/ShellPkg.ci.yaml
  StandaloneMmPkg/StandaloneMmPkg.ci.yaml
  UefiCpuPkg/UefiCpuPkg.ci.yaml
  UnitTestFrameworkPkg/UnitTestFrameworkPkg.ci.yaml
  pip-requirements.txt
Labels: impact:non-functional

#440 Don't Create Variable Policy for PlatformRecovery#### if SetVariable Failed
  MdeModulePkg/Include/Library/UefiBootManagerLib.h
  MdeModulePkg/Library/UefiBootManagerLib/BmLoadOption.c
Labels: impact:security

#433 Introduce notification callbacks for the Policy Service
  PolicyServicePkg/Include/Library/PolicyLib.h
  PolicyServicePkg/Include/PolicyInterface.h
  PolicyServicePkg/Library/DxePolicyLib/DxePolicy.c
  PolicyServicePkg/Library/DxePolicyLib/DxePolicyLib.inf
  PolicyServicePkg/Library/PolicyLibCommon.c
  PolicyServicePkg/PolicyService/DxeMm/PolicyCommon.c
  PolicyServicePkg/PolicyService/DxeMm/PolicyCommon.h
  PolicyServicePkg/PolicyService/DxeMm/PolicyDxe.c
  PolicyServicePkg/PolicyService/DxeMm/PolicyMm.c
  PolicyServicePkg/PolicyService/DxeMm/UnitTest/DxeMmPolicyUnitTest.c
  PolicyServicePkg/PolicyService/DxeMm/UnitTest/DxeMmPolicyUnitTest.inf
  PolicyServicePkg/PolicyService/Pei/PolicyPei.c
  PolicyServicePkg/PolicyService/Pei/PolicyPei.h
  PolicyServicePkg/PolicyService/Pei/PolicyPei.inf
  PolicyServicePkg/PolicyService/Pei/UnitTest/PeiPolicyUnitTest.c
  PolicyServicePkg/PolicyService/Pei/UnitTest/PeiPolicyUnitTest.inf
  PolicyServicePkg/PolicyService/Pei/UnitTest/PeiPolicyUnitTestMocks.c
  PolicyServicePkg/PolicyService/PolicyHob.h
  PolicyServicePkg/PolicyServicePkg.ci.yaml
  PolicyServicePkg/PolicyServicePkg.dec
  PolicyServicePkg/README.md
  PolicyServicePkg/Test/PolicyServicePkgHostTest.dsc
Labels: impact:breaking-change, type:documentation, impact:testing

#441 [CHERRY-PICK] Introduce notification callbacks for the Policy Service (#433)
  PolicyServicePkg/Include/Library/PolicyLib.h
  PolicyServicePkg/Include/PolicyInterface.h
  PolicyServicePkg/Library/DxePolicyLib/DxePolicy.c
  PolicyServicePkg/Library/DxePolicyLib/DxePolicyLib.inf
  PolicyServicePkg/Library/PolicyLibCommon.c
  PolicyServicePkg/PolicyService/DxeMm/PolicyCommon.c
  PolicyServicePkg/PolicyService/DxeMm/PolicyCommon.h
  PolicyServicePkg/PolicyService/DxeMm/PolicyDxe.c
  PolicyServicePkg/PolicyService/DxeMm/PolicyMm.c
  PolicyServicePkg/PolicyService/DxeMm/UnitTest/DxeMmPolicyUnitTest.c
  PolicyServicePkg/PolicyService/DxeMm/UnitTest/DxeMmPolicyUnitTest.inf
  PolicyServicePkg/PolicyService/Pei/PolicyPei.c
  PolicyServicePkg/PolicyService/Pei/PolicyPei.h
  PolicyServicePkg/PolicyService/Pei/PolicyPei.inf
  PolicyServicePkg/PolicyService/Pei/UnitTest/PeiPolicyUnitTest.c
  PolicyServicePkg/PolicyService/Pei/UnitTest/PeiPolicyUnitTest.inf
  PolicyServicePkg/PolicyService/Pei/UnitTest/PeiPolicyUnitTestMocks.c
  PolicyServicePkg/PolicyService/PolicyHob.h
  PolicyServicePkg/PolicyServicePkg.ci.yaml
  PolicyServicePkg/PolicyServicePkg.dec
  PolicyServicePkg/README.md
  PolicyServicePkg/Test/PolicyServicePkgHostTest.dsc
Labels: impact:breaking-change, type:documentation, impact:testing

#443 Removing ARM based tests as this is not supported yet
  PolicyServicePkg/Test/PolicyServicePkgHostTest.dsc
Labels: type:bug

#445 MdeModulePkg/UefiBootManagerLib: Skip con var update if no change
  MdeModulePkg/Library/UefiBootManagerLib/BmConsole.c
Labels: type:enhancement

#447 [CHERRY-PICK] MdeModulePkg/UefiBootManagerLib: Skip con var update if no change (#445)
  MdeModulePkg/Library/UefiBootManagerLib/BmConsole.c
Labels: type:enhancement

#449 UefiDevicePathLib: remove PEIM support
  MdeModulePkg/MdeModulePkg.dsc
  MdePkg/Library/UefiDevicePathLib/UefiDevicePathLib.inf
Labels: impact:breaking-change, impact:non-functional

#450 OverrideValidation: Update logging levels
  BaseTools/Plugin/OverrideValidation/OverrideValidation.py
Labels: language:python, impact:non-functional

#452 BaseTools: Detect invalid library override
  BaseTools/Source/Python/Workspace/WorkspaceCommon.py
Labels: language:python, impact:non-functional

#456 GenFw: auto set nxcompat flag
  BaseTools/Source/C/GenFw/GenFw.c
  BaseTools/Source/C/Include/IndustryStandard/PeImage.h
Labels: impact:security

#457 MdeModulePkgHostTest: UefiSortLib -> SortLib for library overrides
  MdeModulePkg/Library/UefiSortLib/GoogleTest/UefiSortLibGoogleTest.inf
  MdeModulePkg/Library/UefiSortLib/UnitTest/UefiSortLibUnitTest.inf
  MdeModulePkg/Test/MdeModulePkgHostTest.dsc
Labels: impact:non-functional, type:bug

#463 BaseTools: scan Edk2ToolsBuild.py make output
  BaseTools/Edk2ToolsBuild.py
Labels: language:python, impact:non-functional

#469 MdeModule: resolve invalid library override
  MdeModulePkg/Test/MdeModulePkgHostTest.dsc
Labels: impact:non-functional

#468 BaseTools: Remove /NXCOMPAT VS X64 DLINK flags
  BaseTools/Conf/tools_def.template
Labels: impact:non-functional

#472 BaseTools: Use latest release
  BaseTools/Bin/basetoolsbin_ext_dep.yaml
Labels: impact:non-functional

#470 [CodeQL] CryptoPkg: BaseCryptLib: Check return value from `ASN1_get_object`
  CryptoPkg/Library/BaseCryptLib/Pk/CryptX509.c
Labels: impact:security

#473 BaseTools: BinToPcd: replace xdrlib functionality
  BaseTools/Scripts/BinToPcd.py
Labels: language:python, impact:non-functional

#477 .github/label-issues.yml: Use Mu DevOps 4.0.5
  .github/workflows/label-issues.yml
Labels: type:dependencies, impact:non-functional

#479 [CHERRY-PICK] TCBZ 4492: Update SplitTable() Logic to Correctly Break Up Memory Map
  MdeModulePkg/Core/Dxe/Misc/MemoryAttributesTable.c
Labels: type:bug
