Repository microsoft/mu_basecore, pull requests merged in 2024-01, with the labels that each got.

#664 FdSizeReport: Handle empty FV sections in Build Report
  BaseTools/Plugin/FdSizeReport/FdSizeReportGenerator.py
Labels: language:python, impact:non-functional

#665 Update Memory Protection Special Region Logic to Handle Edge Case
  MdeModulePkg/Core/Dxe/Misc/MemoryProtectionSupport.c
Labels: impact:security, type:bug

#668 Adding MockRNG to the Google Test Mock
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockRng.h
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiBootServicesTableLib/MockUefiBootServicesTableLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/Protocol/MockRng.cpp
Labels: impact:non-functional

#671 Ensure Stack Guard Init is Performed Regardless of Platform NX Policy
  MdeModulePkg/Core/Dxe/Misc/MemoryProtectionSupport.c
Labels: impact:security, type:bug

#670 .git-blame-ignore-revs: Ignore Line Ending and Uncrustify only commits
  .git-blame-ignore-revs
Labels: impact:non-functional, semver:patch

#672 Fix Incorrect Mock RNG Prototypes
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockRng.h
  MdePkg/Test/Mock/Library/GoogleTest/Protocol/MockRng.cpp
Labels: impact:non-functional

#679 CryptoPkg/OpensslLibFull: Add Arm CC flags
  CryptoPkg/Library/OpensslLib/OpensslLibFull.inf
Labels: semver:patch

#681 CryptoPkg: Update shared crypto to 2023.2.6
  CryptoPkg/Driver/Bin/BaseCryptoDriver_ext_dep.json
Labels: impact:security, semver:patch

#682 BaseTools: Add Cargo Feature support for build
  BaseTools/Conf/build_rule.template
  BaseTools/Source/Python/AutoGen/GenMake.py
Labels: language:python, impact:breaking-change, impact:non-functional

#688 Update pytool dependency
  BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
  pip-requirements.txt
Labels: language:python, impact:breaking-change, impact:non-functional

#686 Removed .pytool CodeQL and instead use the BaseTools version inherited from edk2
  .github/workflows/codeql.yml
  .pytool/CISettings.py
  .pytool/Plugin/CodeQL/CodeQlAnalyzePlugin.py
  .pytool/Plugin/CodeQL/CodeQlAnalyze_plug_in.yaml
  .pytool/Plugin/CodeQL/CodeQlBuildPlugin.py
  .pytool/Plugin/CodeQL/CodeQlBuild_plug_in.yaml
  .pytool/Plugin/CodeQL/MuCodeQlQueries.qls
  .pytool/Plugin/CodeQL/Readme.md
  .pytool/Plugin/CodeQL/analyze/__init__.py
  .pytool/Plugin/CodeQL/analyze/analyze_filter.py
  .pytool/Plugin/CodeQL/analyze/globber.py
  .pytool/Plugin/CodeQL/codeqlcli_ext_dep.yaml
  .pytool/Plugin/CodeQL/codeqlcli_linux_ext_dep.yaml
  .pytool/Plugin/CodeQL/codeqlcli_windows_ext_dep.yaml
  .pytool/Plugin/CodeQL/common/__init__.py
  .pytool/Plugin/CodeQL/common/codeql_plugin.py
  .pytool/Plugin/CodeQL/integration/__init__.py
  .pytool/Plugin/CodeQL/integration/stuart_codeql.py
  BaseTools/Plugin/CodeQL/codeqlcli_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_linux_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_windows_ext_dep.yaml
Labels: impact:non-functional

#691 [CHERRY-PICK] .pytool/Plugin: UncrustifyCheck: use stat instead of os.stat
  .pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py
Labels: impact:non-functional

#696 CryptoPkg/generate_cryptodriver.py: Fix Crypto protocol include path
  CryptoPkg/Driver/Packaging/generate_cryptodriver.py
Labels: language:python, impact:non-functional, type:bug

#700 Add MuCodeQlQueries.qls and update the CodeQlAnalyzePlugin to use it
  BaseTools/Plugin/CodeQL/CodeQlAnalyzePlugin.py
  BaseTools/Plugin/CodeQL/MuCodeQlQueries.qls
  BaseTools/Plugin/CodeQL/Readme.md
Labels: language:python, impact:non-functional, type:bug

#701 [CHERRY-PICK] Update pytool dependency (#688)
  BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
  pip-requirements.txt
Labels: language:python, impact:breaking-change, impact:non-functional

#702 MdePkg/CompilerIntrinsicsLib: Add IntrinsicLib class and strcmp
  MdePkg/Library/CompilerIntrinsicsLib/ArmCompilerIntrinsicsLib.inf
  MdePkg/Library/CompilerIntrinsicsLib/strcmp.c
Labels: type:design-change

#703 [CHERRY-PICK] MdePkg/CompilerIntrinsicsLib: Add IntrinsicLib class and strcmp
  MdePkg/Library/CompilerIntrinsicsLib/ArmCompilerIntrinsicsLib.inf
  MdePkg/Library/CompilerIntrinsicsLib/strcmp.c
Labels: type:design-change
