Repository microsoft/mu_basecore, pull requests merged in 2024-09, with the labels that each got.

#1130 Update ReadMe.rst to add mock-related breaking changes
  ReadMe.rst
Labels: impact:non-functional, type:documentation

#1134 [CHERRY-PICK] MdeModulePkg/FaultTolerantWriteDxe: Fix buffer overrun issue
  MdeModulePkg/Universal/FaultTolerantWriteDxe/FtwMisc.c
Labels: impact:non-functional

#1109 Add mock functions under MockUefiRuntimeServicesTableLib, MockUefiRuntimeServicesTableLib and Create Mock for DxeServicesTableLib
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockDxeServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiBootServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiRuntimeServicesTableLib.h
  MdePkg/Test/Mock/Library/GoogleTest/MockDxeServicesTableLib/MockDxeServicesTableLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockDxeServicesTableLib/MockDxeServicesTableLib.inf
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiBootServicesTableLib/MockUefiBootServicesTableLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiRuntimeServicesTableLib/MockUefiRuntimeServicesTableLib.cpp
Labels: impact:non-functional

#1122 Mock Functions for ReportStatusCodeHandler Library & RegistryNotify , ConnectController in MockUefiBootServicesTableLib
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiBootServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Ppi/MockPeiReportStatusCodeHandler.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockReportStatusCodeHandler.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockSmmReportStatusCodeHandler.h
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiBootServicesTableLib/MockUefiBootServicesTableLib.cpp
Labels: impact:non-functional, impact:testing

#1139 [CHERRY-PICK] MdePkg: Bring in mocks from 2311
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockDxeServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiBootServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiRuntimeServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Ppi/MockPeiReportStatusCodeHandler.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockReportStatusCodeHandler.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockSmmReportStatusCodeHandler.h
  MdePkg/Test/Mock/Library/GoogleTest/MockDxeServicesTableLib/MockDxeServicesTableLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockDxeServicesTableLib/MockDxeServicesTableLib.inf
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiBootServicesTableLib/MockUefiBootServicesTableLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiRuntimeServicesTableLib/MockUefiRuntimeServicesTableLib.cpp
Labels: impact:non-functional

#1141 [202311] ImageValidation.py: Support gitignore style syntax for file exclusion
  .pytool/Plugin/ImageValidation/ImageValidation.py
  .pytool/Plugin/ImageValidation/ReadMe.md
Labels: impact:non-functional

#1142 .pytool/ImageValidation: Print invalid dir paths
  .pytool/Plugin/ImageValidation/ImageValidation.py
Labels: impact:non-functional

#1140 [SQUASH ON REBASE] ImageValidation.py: Support gitignore style syntax for file exclusion
  .pytool/Plugin/ImageValidation/ImageValidation.py
  .pytool/Plugin/ImageValidation/ReadMe.md
Labels: impact:non-functional

#1155 [CHERRY-PICK] .pytool/ImageValidation: Print invalid dir paths
  .pytool/Plugin/ImageValidation/ImageValidation.py
Labels: impact:non-functional

#1153 [CHERRY-PICK][REBASE&FF] MdeModulePkg/SMM: Initialize 'WillReturn' variable
  MdeModulePkg/Core/PiSmmCore/Smi.c
Labels: impact:non-functional, type:bug

#1157 CryptoPkg: Require exact crypto version match
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/DxeCryptLib.c
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/PeiCryptLib.c
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/RuntimeDxeCryptLib.c
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/SmmCryptLib.c
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/StandaloneMmCryptLib.c
Labels: type:design-change

#1154 [CHERRY-PICK][REBASE&FF] ImageValidation.py: Support gitignore style syntax for file exclusion
  .pytool/Plugin/ImageValidation/ImageValidation.py
  .pytool/Plugin/ImageValidation/ReadMe.md
Labels: impact:non-functional

#1159 [REBASE&FF] MdeModulePkg/SMM: Initialize 'WillReturn' variable
  MdeModulePkg/Core/PiSmmCore/Smi.c
Labels: impact:non-functional

#1160 [REBASE&FF] CryptoPkg: Require exact crypto version match
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/DxeCryptLib.c
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/PeiCryptLib.c
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/RuntimeDxeCryptLib.c
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/SmmCryptLib.c
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/StandaloneMmCryptLib.c
Labels: type:design-change

#1106 Add mock functions under MockUefiLib and Create Mock for AcpiTable, FirmwareVolume2 and AcpiSystemDescriptionTable protocol
  MdeModulePkg/Bus/Pci/PciBusDxe/PciLib.c
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockDxeServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiBootServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiRuntimeServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Ppi/MockPeiReportStatusCodeHandler.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockAcpiSystemDescriptionTable.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockAcpiTable.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockFirmwareVolume2.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockReportStatusCodeHandler.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockSmmReportStatusCodeHandler.h
  MdePkg/Test/Mock/Library/GoogleTest/MockDxeServicesTableLib/MockDxeServicesTableLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockDxeServicesTableLib/MockDxeServicesTableLib.inf
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiBootServicesTableLib/MockUefiBootServicesTableLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiLib/MockUefiLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiRuntimeServicesTableLib/MockUefiRuntimeServicesTableLib.cpp
  NetworkPkg/UefiPxeBcDxe/PxeBcBoot.c
  NetworkPkg/UefiPxeBcDxe/PxeBcImpl.c
  NetworkPkg/UefiPxeBcDxe/PxeBcImpl.h
  NetworkPkg/UefiPxeBcDxe/UefiPxeBcDxe.inf
Labels: impact:non-functional, impact:testing

#1165 MdePkg: Add mocks for AcpiTable and more
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockAcpiSystemDescriptionTable.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockAcpiTable.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockFirmwareVolume2.h
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiLib/MockUefiLib.cpp
Labels: impact:non-functional, impact:testing

#1167 [CHERRY-PICK] MdePkg: Add mocks for AcpiTable and more
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockAcpiSystemDescriptionTable.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockAcpiTable.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockFirmwareVolume2.h
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiLib/MockUefiLib.cpp
Labels: impact:non-functional
