Repository microsoft/mu_basecore, pull requests merged in 2024-05, with the labels that each got.

#838 Make DEBUG_ERROR Messages on Memory Protection Hob Mismatch More Explicit
  MdeModulePkg/Library/MemoryProtectionHobLib/DxeMemoryProtectionHobLib.c
  MdeModulePkg/Library/MemoryProtectionHobLib/MmCommonMemoryProtectionHobLib.c
Labels: impact:non-functional

#842 RustEnvironmentCheck: Check for corrupted components
  BaseTools/Plugin/RustEnvironmentCheck/RustEnvironmentCheck.py
Labels: type:enhancement, language:python, impact:non-functional

#844 [CHERRY-PICK] MdePkg/IndustryStandard: Add _PSD/_CPC/Coord types definitions
  MdePkg/Include/IndustryStandard/Acpi30.h
  MdePkg/Include/IndustryStandard/Acpi40.h
  MdePkg/Include/IndustryStandard/Acpi50.h
  MdePkg/Include/IndustryStandard/Acpi51.h
  MdePkg/Include/IndustryStandard/Acpi60.h
  MdePkg/Include/IndustryStandard/Acpi61.h
  MdePkg/Include/IndustryStandard/Acpi62.h
  MdePkg/Include/IndustryStandard/Acpi63.h
  MdePkg/Include/IndustryStandard/Acpi64.h
  MdePkg/Include/IndustryStandard/Acpi65.h
Labels: impact:non-functional

#850 CryptoPkg: Update shared crypto to 2023.2.9
  CryptoPkg/Driver/Bin/BaseCryptoDriver_ext_dep.json
Labels: type:bug

#853 CodeQL: Update from 2.16.1 to 2.17.3
  BaseTools/Plugin/CodeQL/codeqlcli_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_linux_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_windows_ext_dep.yaml
Labels: impact:non-functional, semver:patch

#854 CodeQL: Update from 2.15.4 to 2.17.3
  .pytool/Plugin/CodeQL/codeqlcli_ext_dep.yaml
  .pytool/Plugin/CodeQL/codeqlcli_linux_ext_dep.yaml
  .pytool/Plugin/CodeQL/codeqlcli_windows_ext_dep.yaml
Labels: impact:non-functional, semver:patch

#824 [Release/202302] Updates NetworkPkg/SecurityFixes.yaml to reflect the current state of CVE patche
  NetworkPkg/SecurityFixes.yaml
Labels: impact:non-functional, type:documentation

#852 BinToPcd.py: Remove xdrlib import
  BaseTools/Scripts/BinToPcd.py
Labels: language:python, impact:non-functional

#855 Supports ARM Platforms without needing to disable PcdEnforceSecureRngAlgorithms
  NetworkPkg/Library/DxeNetLib/DxeNetLib.c
  NetworkPkg/Library/DxeNetLib/DxeNetLib.inf
Labels: impact:security

#860 MdeModulePkg/HiiDatabaseDxe: Correcting a Codeql change
  MdeModulePkg/Universal/HiiDatabaseDxe/Database.c
Labels: type:bug

#861 MdeModulePkg\DxeCore: BS memory allocated from SMM Entry points is still RP
  MdeModulePkg/Core/Dxe/Misc/MemoryProtection.c
Labels: type:bug

#875 [CHERRY-PICK] UefiCpuPkg: change name of gMpInformationHobGuid2
  UefiCpuPkg/CpuMpPei/CpuMpPei.c
  UefiCpuPkg/CpuMpPei/CpuMpPei.inf
  UefiCpuPkg/Include/Guid/MpInformation2.h
  UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.c
  UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.inf
  UefiCpuPkg/UefiCpuPkg.dec
Labels: impact:breaking-change, impact:non-functional

#878 Fixing an edge case in AutoGen script where BUILDMODULE might fail
  BaseTools/Source/Python/AutoGen/GenC.py
Labels: language:python

#880 [CHERRY-PICK] [Release/202302] NetworkPkg TcpDxe: Fixed system stuck on PXE boot flow in iPXE environment
  NetworkPkg/TcpDxe/TcpDriver.c
Labels: type:bug
