Repository microsoft/mu_basecore, pull requests merged in 2024-08, with the labels that each got.

#1087 Create Mock for IsaHc protocol
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockIsaHc.h
  MdePkg/Test/Mock/Library/GoogleTest/Protocol/MockIsaHc.cpp
Labels: impact:non-functional, impact:testing

#1084 Add mock functions under MockPciIoProtocol and Create Mock for Smbio, UsbIo and NvmExpressPassthru protocol
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockNvmExpressPassthru.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockPciIoProtocol.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockSmbios.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockUsbIo.h
  MdePkg/Test/Mock/Library/GoogleTest/Protocol/MockNvmExpressPassthru.cpp
  MdePkg/Test/Mock/Library/GoogleTest/Protocol/MockPciIoProtocol.cpp
  MdePkg/Test/Mock/Library/GoogleTest/Protocol/MockSmbios.cpp
  MdePkg/Test/Mock/Library/GoogleTest/Protocol/MockUsbIo.cpp
Labels: impact:non-functional, impact:testing

#1088 Create the Google Test mocks for SmmBase2 Protocol.
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockSmmBase2.h
  MdePkg/Test/Mock/Library/GoogleTest/Protocol/MockSmmBase2.cpp
Labels: impact:non-functional, impact:testing

#1086 [SQUASH ON REBASE] Revert "MdePkg/CompilerIntrinsicsLib: Add IntrinsicLib class and strcmp"
  MdePkg/Library/CompilerIntrinsicsLib/ArmCompilerIntrinsicsLib.inf
  MdePkg/Library/CompilerIntrinsicsLib/strcmp.c
Labels: impact:breaking-change, impact:non-functional, type:design-change

#1085 [2405][SQUASH ON REBASE] Revert "MdePkg/CompilerIntrinsicsLib: Add IntrinsicLib class and strcmp"
  MdePkg/Library/CompilerIntrinsicsLib/ArmCompilerIntrinsicsLib.inf
  MdePkg/Library/CompilerIntrinsicsLib/strcmp.c
Labels: impact:breaking-change, impact:non-functional, type:design-change

#1096 [Cherry-Pick] UefiCpuPkg: Add PcdCpuSmmApSyncTimeout2 PCD
  UefiCpuPkg/UefiCpuPkg.dec
  UefiCpuPkg/UefiCpuPkg.uni
Labels: impact:non-functional

#1098 BaseTools/build_rule.template: Set additional Rust module linker flags
  BaseTools/Conf/build_rule.template
Labels: impact:breaking-change, impact:non-functional

#1089 [202405][REBASE&FF] Variable Argument List macros reversions
  MdePkg/Include/Base.h
Labels: impact:breaking-change, impact:non-functional

#1095 Revert Downgrading Page.c Error Prints
  MdeModulePkg/Core/Dxe/Mem/Page.c
Labels: impact:non-functional

#1099 MdePkg: Create Google mock for ReadOnlyVariable2
  MdePkg/Test/Mock/Include/GoogleTest/Ppi/MockReadOnlyVariable2.h
  MdePkg/Test/Mock/Library/GoogleTest/Ppi/MockReadOnlyVariable2.cpp
Labels: impact:non-functional, impact:testing

#1102 [Release/202405] Moves placement of variable policy registration to after the last variable that is "Read-Only"
  MdeModulePkg/Universal/BdsDxe/BdsEntry.c
Labels: type:bug

#1103 [2405] BaseTools/build_rule.template: Set additional Rust module linker flags
  BaseTools/Conf/build_rule.template
Labels: impact:breaking-change, impact:non-functional

#1100 ImageValidation: Add default configuration
  .pytool/Plugin/ImageValidation/ImageValidation.py
  .pytool/Plugin/ImageValidation/ReadMe.md
  .pytool/Plugin/ImageValidation/image_validation.cfg
Labels: impact:breaking-change, impact:non-functional, type:documentation, type:design-change

#1104 [REBASE&FF][CHERRY-PICK] ImageValidation: Add default configuration
  .pytool/Plugin/ImageValidation/ImageValidation.py
  .pytool/Plugin/ImageValidation/ReadMe.md
  .pytool/Plugin/ImageValidation/image_validation.cfg
Labels: impact:breaking-change, impact:non-functional, type:documentation

#1094 Create mocks for PlatformHookLib and PciLib
  MdeModulePkg/Test/MdeModulePkgHostTest.dsc
  MdeModulePkg/Test/Mock/Include/GoogleTest/Library/MockPlatformHookLib.h
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockPlatformHookLib/MockPlatformHookLib.cpp
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockPlatformHookLib/MockPlatformHookLib.inf
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockPciLib.h
  MdePkg/Test/Mock/Library/GoogleTest/MockPciLib/MockPciLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockPciLib/MockPciLib.inf
Labels: impact:non-functional, impact:testing

#1108 BaseTools/build_rule.template: Add FILE_GUID to the environment for Rust modules
  BaseTools/Conf/build_rule.template
Labels: type:enhancement, impact:non-functional

#1110 [2405] BaseTools/build_rule.template: Add FILE_GUID to the environment for Rust modules
  BaseTools/Conf/build_rule.template
Labels: type:enhancement, impact:non-functional

#1107 Updated Release notes.
  ReadMe.rst
Labels: impact:non-functional

#1079 [Cherry-Pick] Updating Shared Crypto Bin to version 2023.12.2.
  CryptoPkg/Binaries/BaseCryptoDriver_ext_dep.json
Labels: impact:breaking-change, impact:non-functional

#1120 pip: Update all pip-requirements to latest.
  pip-requirements.txt
Labels: impact:non-functional

#1125 [202311] ImageValidation: Determine profile from inf MODULE_TYPE
  .pytool/Plugin/ImageValidation/ImageValidation.py
Labels: impact:non-functional

#1124 [202405] ImageValidation: Determine profile from inf MODULE_TYPE
  .pytool/Plugin/ImageValidation/ImageValidation.py
Labels: impact:non-functional

#1111 Add mock functions under MockUefiLib and Create Mock for CapsuleLib, PerformanceLib, MockUefiBootManagerLib and GenericMemoryTestProtocol
  MdeModulePkg/Test/MdeModulePkgHostTest.dsc
  MdeModulePkg/Test/Mock/Include/GoogleTest/Library/MockCapsuleLib.h
  MdeModulePkg/Test/Mock/Include/GoogleTest/Library/MockUefiBootManagerLib.h
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockCapsuleLib/MockCapsuleLib.cpp
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockCapsuleLib/MockCapsuleLib.inf
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockUefiBootManagerLib/MockUefiBootManagerLib.cpp
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockUefiBootManagerLib/MockUefiBootManagerLib.inf
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockPerformanceLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockGenericMemoryTest.h
  MdePkg/Test/Mock/Library/GoogleTest/MockPerformanceLib/MockPerformanceLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockPerformanceLib/MockPerformanceLib.inf
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiLib/MockUefiLib.cpp
Labels: impact:non-functional

#1127 [202405] ImageValidation.py: Don't parse entire image
  .pytool/Plugin/ImageValidation/ImageValidation.py
Labels: impact:non-functional

#1126 [202311] ImageValidation.py: Don't parse entire image
  .pytool/Plugin/ImageValidation/ImageValidation.py
Labels: impact:non-functional
