Repository microsoft/mu_basecore, pull requests merged in 2024-07, with the labels that each got.

#958 Add support for HTTP error 429
  MdePkg/Include/Protocol/Http.h
  NetworkPkg/Library/DxeHttpLib/DxeHttpLib.c
Labels: impact:non-functional

#964 Renaming various test .infs to match convention
  MdeModulePkg/Application/SmiHandlerProfileInfo/SmiHandlerProfileAuditTestApp.inf
  MdeModulePkg/MdeModulePkg.dsc
  MdePkg/MdePkg.dsc
  MdePkg/Test/UnitTest/Library/BaseLib/BaseLibUnitTestApp.inf
  MdePkg/Test/UnitTest/Library/BaseSafeIntLib/TestBaseSafeIntLibTestApp.inf
Labels: impact:non-functional, impact:testing

#1022 MdeModulePkg: SMI Profiler changes.
  MdeModulePkg/Application/SmiHandlerProfileInfo/SmiHandlerProfileAuditTestApp.inf
  MdeModulePkg/Application/SmiHandlerProfileInfo/SmiHandlerProfileInfo.c
  MdeModulePkg/Core/PiSmmCore/SmiHandlerProfile.c
Labels: impact:non-functional, impact:testing

#1027 MdeModulePkg: Localize the mInternalRT global var in RuntimeResetSystemLib
  MdeModulePkg/Library/RuntimeResetSystemLib/RuntimeResetSystemLib.c
Labels: impact:non-functional

#1024 MdeModulePkg: Removed PeiAllocatePool Assert
  MdeModulePkg/Core/Pei/Memory/MemoryServices.c
Labels: impact:non-functional

#1011 TCBZ2586: Fixed PcdValueInit generation on linux
  BaseTools/Source/Python/Workspace/DscBuildData.py
Labels: language:python, impact:non-functional, type:bug

#925 [Rebase & FF] 202405: PCD Loader feature cherry-pick
  MdeModulePkg/Include/Library/PcdDatabaseLoaderLib.h
  MdeModulePkg/Library/PcdDatabaseLoaderLib/Dxe/PcdDatabaseLoaderLibDxe.c
  MdeModulePkg/Library/PcdDatabaseLoaderLib/Dxe/PcdDatabaseLoaderLibDxe.inf
  MdeModulePkg/Library/PcdDatabaseLoaderLib/Pei/PcdDatabaseLoaderLibPei.c
  MdeModulePkg/Library/PcdDatabaseLoaderLib/Pei/PcdDatabaseLoaderLibPei.inf
  MdeModulePkg/MdeModulePkg.dec
  MdeModulePkg/MdeModulePkg.dsc
  MdeModulePkg/Universal/PCD/Dxe/Pcd.inf
  MdeModulePkg/Universal/PCD/Dxe/Service.c
  MdeModulePkg/Universal/PCD/Dxe/Service.h
  MdeModulePkg/Universal/PCD/Pei/Pcd.c
  MdeModulePkg/Universal/PCD/Pei/Pcd.inf
  MdeModulePkg/Universal/PCD/Pei/Service.c
  MdeModulePkg/Universal/PCD/Pei/Service.h
Labels: impact:breaking-change

#919 [Rebase & FF] 202405: Changes related to upstream unit test code coverage
  BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
  UnitTestFrameworkPkg/ReadMe.md
Labels: language:python, impact:breaking-change

#903 [Rebase & FF] 202405: BaseTools/WinRcPath: Improve Performance.
  BaseTools/Plugin/WindowsResourceCompiler/WinRcPath.py
Labels: language:python

#971 MdePkg/Include/IndustryStandard/IoRemappingTable: Update IORT SMMUv3 flags to include dirty state. [Rebase & FF]
  MdePkg/Include/IndustryStandard/IoRemappingTable.h
Labels: impact:non-functional

#986 MdeModulePkg/MemoryTypeInfoSecVarCheckLib: Elaborate on expected mem. [Rebase & FF]
  MdeModulePkg/Library/MemoryTypeInfoSecVarCheckLib/MemoryTypeInfoSecVarCheckLib.c
Labels: impact:non-functional

#987 BaseTools/Scripts/BinToPcd.py: Update regex strings to use raw strings. [Rebase & FF]
  BaseTools/Scripts/BinToPcd.py
Labels: language:python, impact:non-functional

#989 MdePkg/Include/Protocol/BootManagerPolicy.h: Define GUID for connecting storage devices. [Rebase & FF]
  MdePkg/Include/Protocol/BootManagerPolicy.h
  MdePkg/MdePkg.dec
Labels: impact:non-functional

#995 MdePkg/Include/Register/Intel/StmApi.h: Add SMM_REV_ID definition for STM header. [Rebase & FF]
  MdePkg/Include/Register/Intel/StmApi.h
Labels: impact:non-functional

#997 .gitattributes: Prevent line ending conversion. [Rebase & FF]
  .gitattributes
Labels: impact:non-functional

#1032 SecurityLockLib to log security milestones. [Rebase & FF]
  MdeModulePkg/Core/PiSmmCore/PiSmmIpl.c
  MdeModulePkg/Core/PiSmmCore/PiSmmIpl.inf
  MdeModulePkg/Include/Library/SecurityLockAuditLib.h
  MdeModulePkg/Library/SecurityLockAuditDebugMessageLib/SecurityLockAuditDebugMessageLib.c
  MdeModulePkg/Library/SecurityLockAuditDebugMessageLib/SecurityLockAuditDebugMessageLib.inf
  MdeModulePkg/Library/SecurityLockAuditLibNull/SecurityLockAuditLibNull.c
  MdeModulePkg/Library/SecurityLockAuditLibNull/SecurityLockAuditLibNull.inf
  MdeModulePkg/MdeModulePkg.dec
  MdeModulePkg/MdeModulePkg.dsc
  MdeModulePkg/Universal/CapsuleRuntimeDxe/CapsuleRuntimeDxe.inf
  MdeModulePkg/Universal/CapsuleRuntimeDxe/CapsuleService.c
Labels: impact:non-functional

#1007 Changed gEfiMdeModulePkgTokenSpaceGuid.PcdHiiOsRuntimeSupport default value to FALSE
  MdeModulePkg/MdeModulePkg.dec
Labels: impact:breaking-change

#1037 BaseTools/Plugin/RustEnvironmentCheck: Use pytools Rust helpers
  BaseTools/Plugin/RustEnvironmentCheck/RustEnvironmentCheck.py
  BaseTools/Plugin/RustEnvironmentCheck/RustEnvironmentCheck_plug_in.yaml
  pip-requirements.txt
Labels: language:python, impact:non-functional, type:design-change

#1038 [CHERRY-PICK] BaseTools/Plugin/RustEnvironmentCheck: Use pytools Rust helpers
  BaseTools/Plugin/RustEnvironmentCheck/RustEnvironmentCheck.py
  BaseTools/Plugin/RustEnvironmentCheck/RustEnvironmentCheck_plug_in.yaml
  pip-requirements.txt
Labels: language:python, impact:non-functional, type:design-change

#1030 MdeModulePkg: Compatibility Mode: Only Remap System Memory Regions
  MdeModulePkg/Core/Dxe/DxeMain.inf
  MdeModulePkg/Core/Dxe/Misc/MemoryProtectionSupport.c
Labels: impact:security

#1040 Revert `NO_ABSOLUTE_RELOCS_IN_TEXT` MU change for GCC
  UefiCpuPkg/Library/CpuExceptionHandlerLib/SmmCpuExceptionHandlerLib.inf
Labels: impact:non-functional

#1039 [Cherry-Pick] BaseTools/HostBasedUnitTestRunner: Promote Unittest error to CI fail.
  BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
Labels: language:python, impact:breaking-change, impact:non-functional

#1041 [202405] Revert `NO_ABSOLUTE_RELOCS_IN_TEXT` MU change for GCC
  UefiCpuPkg/Library/CpuExceptionHandlerLib/SmmCpuExceptionHandlerLib.inf
Labels: impact:non-functional

#1042 [Cherry-Pick] BaseTools/HostBasedUnitTestRunner: Promote Unittest error to CI fail.
  BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
Labels: language:python, impact:breaking-change, impact:non-functional

#1048 [Rebase & FF] 202405: MdeModulePkg: VariableStandaloneMm.c - TCG MOR workaround for Standalone MM
  MdeModulePkg/Universal/Variable/RuntimeDxe/VariableStandaloneMm.c
Labels: impact:non-functional

#1044 2405: [CHERRY-PICK] BaseTools/CodeQL: Removed unused static function query
  BaseTools/Plugin/CodeQL/CodeQlQueries.qls
Labels: impact:non-functional, semver:patch

#1047 [Rebase & FF] 202405: MdeModulePkg: UsbEnumer.c - Reset USB port during enumeration if GetPortStatus returns device error
  MdeModulePkg/Bus/Usb/UsbBusDxe/UsbEnumer.c
Labels: impact:non-functional

#1043 [CHERRY-PICK] [Rebase & FF] 202405: MdePkg/UefiDebugLibDebugPortProtocol: make ExitBootServicesCallback() static
  MdePkg/Library/UefiDebugLibDebugPortProtocol/DebugLibConstructor.c
Labels: impact:non-functional

#1051 [Rebase & FF] 202405: MdePkg: Added definition of AMD specific public MSRs
  MdePkg/Include/Register/Amd/ArchitecturalMsr.h
  MdePkg/Include/Register/Amd/Msr.h
Labels: impact:non-functional

#1049 [REBASE&FF][202405] Restore TPL requirements for WaitForEvent()
  MdeModulePkg/Core/Dxe/DxeMain.h
  MdeModulePkg/Core/Dxe/DxeMain.inf
  MdeModulePkg/Core/Dxe/DxeMain/DxeMain.c
  MdeModulePkg/Core/Dxe/Event/Event.c
  MdeModulePkg/Include/Protocol/InternalEventServices.h
  MdeModulePkg/MdeModulePkg.dec
Labels: impact:non-functional

#1055 MdePkg/MockUefiLib: Add EfiCreateProtocolNotifyEvent()
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiLib.h
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiLib/MockUefiLib.cpp
Labels: impact:non-functional, impact:testing

#1062 Add MuCodeQlQueries.qls and pin to the 0.9.12 codeq/cpp-queries pack
  BaseTools/Plugin/CodeQL/CodeQlAnalyzePlugin.py
  BaseTools/Plugin/CodeQL/MuCodeQlQueries.qls
  BaseTools/Plugin/CodeQL/Readme.md
  BaseTools/Plugin/CodeQL/codeqlcli_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_linux_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_windows_ext_dep.yaml
Labels: language:python, impact:non-functional

#1068 [2405] [SQUASH ON REBASE] Fix pip-requirement double listing
  pip-requirements.txt
Labels: impact:non-functional

#1069 BaseTools/codeql: Update to CodeQL 2.18.1
  BaseTools/Plugin/CodeQL/codeqlcli_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_linux_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_windows_ext_dep.yaml
Labels: impact:non-functional

#1072 BaseTools/codeql: Update to CodeQL 2.18.1
  BaseTools/Plugin/CodeQL/codeqlcli_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_linux_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_windows_ext_dep.yaml
Labels: impact:non-functional

#1067 2405: BaseTools/MuCodeQlQueries.qls: Removed unused static function query
  BaseTools/Plugin/CodeQL/MuCodeQlQueries.qls
Labels: impact:non-functional, semver:patch

#1065 Change CpuDeadLoops to panic calls in PiSmmCpuDxeSmm.c
  UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.c
  UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.h
  UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.inf
Labels: impact:non-functional

#1063 BaseTools: GenC: Fixing an edge case where BUILDMODULE might fail
  BaseTools/Source/Python/AutoGen/GenC.py
Labels: language:python

#1034 Update BaseCryptLib tests to reference the PCDs before running
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/AeadAesGcmTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/BaseCryptLibUnitTestApp.inf
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/BlockCipherTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/BnTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/DhTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/EcTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/HkdfTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/HmacTests.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestBaseCryptLibHost.inf
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/X509Tests.c
Labels: impact:non-functional, impact:testing

#1070 [Rebase & FF] Enabled pipelines and CodeQL for PolicyServicePkg
  .azurepipelines/Ubuntu-GCC5.yml
  .azurepipelines/Windows-VS.yml
  .github/codecov.yml
  PolicyServicePkg/PolicyServicePkg.dsc
  PolicyServicePkg/README.md
Labels: impact:non-functional

#1064 [CHERRY-PICK] UefiCpuPkg:fix issue when splitting paging entry
  UefiCpuPkg/Library/CpuPageTableLib/CpuPageTableMap.c
Labels: impact:non-functional

#742 Add deprecation warning support to OverrideValidation plugin
  BaseTools/Plugin/OverrideValidation/OverrideValidation.py
  BaseTools/Plugin/OverrideValidation/OverrideValidation_plug_in.json
  BaseTools/Plugin/OverrideValidation/ReadMe.md
Labels: language:python, impact:non-functional

#1080 [SQUASH ON REBASE] MdeModulePkg: UefiBootManagerLib: Move SetVariableCall
  MdeModulePkg/Library/UefiBootManagerLib/BmLoadOption.c
Labels: type:bug

#1078 Added MockServiceBinding and Add mock functions under MockUefiBootServicesTableLib, MockUefiLib and MockUefiDevicePathLib
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiBootServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiDevicePathLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockServiceBinding.h
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiBootServicesTableLib/MockUefiBootServicesTableLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiDevicePathLib/MockUefiDevicePathLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiLib/MockUefiLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/Protocol/MockServiceBinding.cpp
Labels: impact:non-functional, impact:testing
