Repository microsoft/mu_basecore, pull requests merged in 2024-11, with the labels that each got.

#1207 [Cherry-Pick] Fix naming convention in FirmwareVolume2 gmock
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockFirmwareVolume2.h
Labels: impact:non-functional, type:bug

#1206 [CHERRY-PICK] Added all mock function in MockUefiLib under MdeModulePkg
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiLib.h
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiLib/MockUefiLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiLib/MockUefiLib.inf
Labels: impact:non-functional

#1209 [CHERRY-PICK] UnitTestFrameworkPkg: Use TianoCore mirror of subhook submodule
  .gitmodules
  UnitTestFrameworkPkg/ReadMe.md
Labels: impact:non-functional, type:backport

#1210 [CHERRY-PICK] UnitTestFrameworkPkg: Use TianoCore mirror of subhook s…
  .gitmodules
  UnitTestFrameworkPkg/ReadMe.md
Labels: impact:non-functional

#1211 [CHERRY-PICK] UnitTestFrameworkPkg: Use TianoCore mirror of subhook submodule
  .gitmodules
Labels: impact:non-functional

#1168 Create Mock for PostCodeLib
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockPostCodeLib.h
  MdePkg/Test/Mock/Library/GoogleTest/MockPostCodeLib/MockPostCodeLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockPostCodeLib/MockPostCodeLib.inf
Labels: impact:non-functional, impact:testing, type:backport

#1214 [REBASE & FF] Revert Mu BaseTools Stack Check Change for edk2 Version
  BaseTools/Conf/tools_def.template
Labels: impact:security, type:bug, type:backport

#1220 [TEMPORARY] Disable Stack Cookies for MSVC ARM/AARCH64
  BaseTools/Conf/tools_def.template
Labels: impact:security, impact:non-functional, type:bug, type:backport

#1218 BaseTools HostBasedUnittestRunner Modify CC_REORGANIZE to exclude Null implementations.
  BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
Labels: language:python, type:backport

#1222 BaseTools\HostbasedUnittestRunner: Add support to exclude files from codecoverage. [RB & FF]
  BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
  UnitTestFrameworkPkg/ReadMe.md
Labels: language:python, impact:non-functional, type:backport

#1223 [Cherry-Pick] Declare mock SMM Access2 Protocol. (#1177) [RB & FF]
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockSmmAccess2.h
Labels: impact:non-functional

#1226 [CHERRY-PICK] Create memory bin override library to allow for more extensive platform customization
  MdeModulePkg/Core/Dxe/DxeMain.inf
  MdeModulePkg/Core/Dxe/Mem/Page.c
  MdeModulePkg/Include/Library/MemoryBinOverrideLib.h
  MdeModulePkg/Library/MemoryBinOverrideLibNull/MemoryBinOverrideLibNull.c
  MdeModulePkg/Library/MemoryBinOverrideLibNull/MemoryBinOverrideLibNull.inf
  MdeModulePkg/MdeModulePkg.dec
  MdeModulePkg/MdeModulePkg.dsc
Labels: impact:breaking-change, impact:non-functional, type:backport

#1231 [FF-A] ACPI TPM2 FF-A Changes:
  MdePkg/Include/IndustryStandard/Tpm2Acpi.h
Labels: impact:non-functional

#1229 [Cherry-Pick] MdePkg/SmBios.h: Add new Socket Type for SMBIOS Type4
  MdePkg/Include/IndustryStandard/SmBios.h
Labels: impact:non-functional, type:backport
