Repository microsoft/mu_basecore, pull requests merged in 2024-06, with the labels that each got.

#882 MuCodeQlQueries.qls: Pin to the 0.9.12 codeq/cpp-queries pack
  BaseTools/Plugin/CodeQL/MuCodeQlQueries.qls
  BaseTools/Plugin/CodeQL/codeqlcli_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_linux_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_windows_ext_dep.yaml
Labels: impact:non-functional, semver:patch

#883 MuCodeQlQueries.qls: Pin to the 0.9.12 codeq/cpp-queries pack
  .pytool/Plugin/CodeQL/MuCodeQlQueries.qls
  .pytool/Plugin/CodeQL/codeqlcli_ext_dep.yaml
  .pytool/Plugin/CodeQL/codeqlcli_linux_ext_dep.yaml
  .pytool/Plugin/CodeQL/codeqlcli_windows_ext_dep.yaml
Labels: impact:non-functional, semver:patch

#886 Set EFI_MEMORY_SP as System Memory
  MdeModulePkg/Core/Dxe/Gcd/Gcd.c
Labels: type:bug

#890 Added MockPciIoProtocol and MockLocalApicLib
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockPciIoProtocol.h
  MdePkg/Test/Mock/Library/GoogleTest/Protocol/MockPciIoProtocol.cpp
  UefiCpuPkg/Test/Mock/Include/GoogleTest/Library/MockLocalApicLib.h
  UefiCpuPkg/Test/Mock/Library/GoogleTest/MockLocalApicLib/MockLocalApicLib.cpp
  UefiCpuPkg/Test/Mock/Library/GoogleTest/MockLocalApicLib/MockLocalApicLib.inf
  UefiCpuPkg/Test/UefiCpuPkgHostTest.dsc
  UefiCpuPkg/UefiCpuPkg.dec
Labels: impact:non-functional

#887 [CHERRY-PICK] Pull in fixes in UefiCpuPkg where we can dereference a NULL pointer for mCpuHotPlugData.SmBase
  UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.c
Labels: impact:non-functional

#891 [CHERRY-PICK] [Release/202311] UnitTestFrameworkPkg: Fix Google Test components with multiple files
  UnitTestFrameworkPkg/UnitTestFrameworkPkgHost.dsc.inc
Labels: impact:non-functional, impact:testing, type:bug

#893 [CHERRY-PICK] [Release/202302] UnitTestFrameworkPkg: Fix Google Test components with multiple files
  UnitTestFrameworkPkg/UnitTestFrameworkPkgHost.dsc.inc
Labels: impact:non-functional, impact:testing, type:bug

#897 [CHERRY-PICK] [RELEASE/202311] Pulling PixieFail changes from EDK2 for CVE-2023-45237 and CVE-2023-45236
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiBootServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockHash2.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockRng.h
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiBootServicesTableLib/MockUefiBootServicesTableLib.inf
  NetworkPkg/Dhcp4Dxe/Dhcp4Driver.c
  NetworkPkg/Dhcp6Dxe/Dhcp6Driver.c
  NetworkPkg/DnsDxe/DnsDhcp.c
  NetworkPkg/DnsDxe/DnsImpl.c
  NetworkPkg/HttpBootDxe/HttpBootDhcp6.c
  NetworkPkg/IScsiDxe/IScsiCHAP.c
  NetworkPkg/IScsiDxe/IScsiMisc.c
  NetworkPkg/IScsiDxe/IScsiMisc.h
  NetworkPkg/Include/Library/NetLib.h
  NetworkPkg/Ip4Dxe/Ip4Driver.c
  NetworkPkg/Ip6Dxe/Ip6Driver.c
  NetworkPkg/Ip6Dxe/Ip6If.c
  NetworkPkg/Ip6Dxe/Ip6Nd.c
  NetworkPkg/Ip6Dxe/Ip6Nd.h
  NetworkPkg/Library/DxeNetLib/DxeNetLib.c
  NetworkPkg/Library/DxeNetLib/DxeNetLib.inf
  NetworkPkg/NetworkPkg.dec
  NetworkPkg/SecurityFixes.yaml
  NetworkPkg/TcpDxe/TcpDriver.c
  NetworkPkg/TcpDxe/TcpDxe.inf
  NetworkPkg/TcpDxe/TcpFunc.h
  NetworkPkg/TcpDxe/TcpMain.h
  NetworkPkg/TcpDxe/TcpMisc.c
  NetworkPkg/TcpDxe/TcpTimer.c
  NetworkPkg/Test/NetworkPkgHostTest.dsc
  NetworkPkg/Udp4Dxe/Udp4Driver.c
  NetworkPkg/Udp6Dxe/Udp6Driver.c
  NetworkPkg/UefiPxeBcDxe/GoogleTest/PxeBcDhcp6GoogleTest.cpp
  NetworkPkg/UefiPxeBcDxe/GoogleTest/UefiPxeBcDxeGoogleTest.inf
  NetworkPkg/UefiPxeBcDxe/PxeBcDhcp4.c
  NetworkPkg/UefiPxeBcDxe/PxeBcDriver.c
Labels: impact:security, impact:testing

#898 [CHERRY-PICK] [RELEASE/202302] Pulling PixieFail changes from EDK2 for CVE-2023-45237 and CVE-2023-45236
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiBootServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockHash2.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockRng.h
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiBootServicesTableLib/MockUefiBootServicesTableLib.inf
  NetworkPkg/Dhcp4Dxe/Dhcp4Driver.c
  NetworkPkg/Dhcp6Dxe/Dhcp6Driver.c
  NetworkPkg/DnsDxe/DnsDhcp.c
  NetworkPkg/DnsDxe/DnsImpl.c
  NetworkPkg/HttpBootDxe/HttpBootDhcp6.c
  NetworkPkg/IScsiDxe/IScsiCHAP.c
  NetworkPkg/IScsiDxe/IScsiMisc.c
  NetworkPkg/IScsiDxe/IScsiMisc.h
  NetworkPkg/Include/Library/NetLib.h
  NetworkPkg/Ip4Dxe/Ip4Driver.c
  NetworkPkg/Ip6Dxe/Ip6Driver.c
  NetworkPkg/Ip6Dxe/Ip6If.c
  NetworkPkg/Ip6Dxe/Ip6Nd.c
  NetworkPkg/Ip6Dxe/Ip6Nd.h
  NetworkPkg/Library/DxeNetLib/DxeNetLib.c
  NetworkPkg/Library/DxeNetLib/DxeNetLib.inf
  NetworkPkg/NetworkPkg.dec
  NetworkPkg/SecurityFixes.yaml
  NetworkPkg/TcpDxe/TcpDriver.c
  NetworkPkg/TcpDxe/TcpDxe.inf
  NetworkPkg/TcpDxe/TcpFunc.h
  NetworkPkg/TcpDxe/TcpMain.h
  NetworkPkg/TcpDxe/TcpMisc.c
  NetworkPkg/TcpDxe/TcpTimer.c
  NetworkPkg/Test/NetworkPkgHostTest.dsc
  NetworkPkg/Udp4Dxe/Udp4Driver.c
  NetworkPkg/Udp6Dxe/Udp6Driver.c
  NetworkPkg/UefiPxeBcDxe/GoogleTest/PxeBcDhcp6GoogleTest.cpp
  NetworkPkg/UefiPxeBcDxe/GoogleTest/UefiPxeBcDxeGoogleTest.inf
  NetworkPkg/UefiPxeBcDxe/PxeBcDhcp4.c
  NetworkPkg/UefiPxeBcDxe/PxeBcDriver.c
Labels: impact:security, impact:testing

#899 BaseTools/Plugin/HostBasedUnitTestRunner: Fix invalid escape in HostBasedUnitTest.py
  BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
Labels: language:python, impact:non-functional

#910 Update Crypto Driver to 2023.2.16 for RNG Services
  CryptoPkg/Driver/Bin/BaseCryptoDriver_ext_dep.json
Labels: impact:breaking-change, type:documentation

#909 [CHERRY-PICK] UefiCpuPkg:fix issue when splitting paging entry
  UefiCpuPkg/Library/CpuPageTableLib/CpuPageTableMap.c
Labels: impact:non-functional

#892 Change CpuDeadLoops to panic calls in PiSmmCpuDxeSmm.c
  UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.c
  UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.h
  UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.inf
Labels: impact:non-functional

#920 [CHERRY-PICK] Set EFI_MEMORY_SP as System Memory
  MdeModulePkg/Core/Dxe/Gcd/Gcd.c
Labels: type:bug

#932 .github/workflows: Add label-issues config files
  .github/workflows/label-issues/file-paths.yml
  .github/workflows/label-issues/regex-pull-requests.yml
Labels: type:bug

#933 BaseTools/Plugin/FlattenPdbs: Add plugin
  BaseTools/Plugin/FlattenPdbs/FlattenPdbs.py
  BaseTools/Plugin/FlattenPdbs/FlattenPdbs_plug_in.yaml
Labels: language:python, impact:non-functional, type:feature-request

#896 [Rebase & FF] 202405: Ramdisk alignment
  MdeModulePkg/Library/UefiBootManagerLib/BmBoot.c
Labels: impact:non-functional

#894 [Rebase & FF] 202405: MdeModulePkg: BdsDxe: Introduce infinite boot retries
  MdeModulePkg/MdeModulePkg.dec
  MdeModulePkg/Universal/BdsDxe/BdsDxe.inf
  MdeModulePkg/Universal/BdsDxe/BdsEntry.c
Labels: impact:non-functional

#950 [202405][REBASE&FF] Add FdSizeReportGenerator plugin
  BaseTools/Plugin/FdSizeReport/FdReport_Template.html
  BaseTools/Plugin/FdSizeReport/FdSizeReportGenerator.py
  BaseTools/Plugin/FdSizeReport/FdSizeReportGenerator_plug_in.json
  BaseTools/Plugin/FdSizeReport/ReadMe.md
Labels: language:python, impact:non-functional

#949 [202405] Add NestedPackageCheck plugin
  .pytool/Plugin/NestedPackageCheck/NestedPackageCheck.py
  .pytool/Plugin/NestedPackageCheck/NestedPackageCheck_plug_in.yaml
  .pytool/Plugin/NestedPackageCheck/Readme.md
Labels: impact:non-functional

#948 [202405] Add ImageValidation plugin
  .pytool/Plugin/ImageValidation/ImageValidation.py
  .pytool/Plugin/ImageValidation/ImageValidation_plug_in.yaml
  .pytool/Plugin/ImageValidation/ReadMe.md
Labels: impact:non-functional

#977 .github/workflows/codeql.yml: Add retry on GitHub REST Access Failures
  .github/workflows/codeql.yml
Labels: impact:non-functional, semver:patch

#970 MdePkg/Test: Create a host-based implementation of RngLib [Rebase & FF]
  MdePkg/Test/Library/RngLibHostTestLfsr/RngLibHostTestLfsr.c
  MdePkg/Test/Library/RngLibHostTestLfsr/RngLibHostTestLfsr.inf
  MdePkg/Test/MdePkgHostTest.dsc
Labels: impact:non-functional, impact:testing

#837 Host Based Unit Test updates
  BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
  UnitTestFrameworkPkg/ReadMe.md
  UnitTestFrameworkPkg/UnitTestFrameworkPkg.ci.yaml
Labels: language:python, impact:breaking-change, impact:non-functional, type:documentation

#944 IndustryStandard\IpmiNetFnSensorEvent.h: Added SetSensorThreshold and GetSensorThreshold commands [Rebase & FF]
  MdePkg/Include/IndustryStandard/IpmiNetFnSensorEvent.h
Labels: impact:non-functional

#955 Fix missing logs from GenMake.py
  BaseTools/Source/Python/AutoGen/GenMake.py
Labels: language:python, impact:non-functional, type:bug

#946 Add extra RestoreTpl() call in DiskIo and StartImage() to maintain TPL raise/restore symmetry [Rebase & FF]
  MdeModulePkg/Core/Dxe/Image/Image.c
  MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIo.c
Labels: impact:non-functional

#947 Enable Data Terminal Ready and Request to Send at the end of a Serial
  MdeModulePkg/Universal/Console/TerminalDxe/TerminalConIn.c
Labels: type:bug

#959 UefiBootManagerLib: Update assert condition in BmFindBootOptionInVariable
  MdeModulePkg/Library/UefiBootManagerLib/BmBoot.c
Labels: impact:non-functional, type:bug

#960 Fix buffer overflow when merging guard pages in MergeMemoryMap
  MdeModulePkg/Core/Dxe/Misc/MemoryAttributesTable.c
Labels: impact:non-functional, type:bug

#965 Add code to block on AP execution if a task is in progress.
  UefiCpuPkg/CpuMpPei/CpuMpPei.c
  UefiCpuPkg/Library/MpInitLib/PeiMpLib.c
Labels: impact:non-functional
