Repository microsoft/mu_basecore, pull requests merged in 2024-04, with the labels that each got.

#785 BaseTools: InfBuildData: Fix Private dec data retrieval
  BaseTools/Source/Python/Workspace/InfBuildData.py
Labels: language:python, impact:non-functional, type:bug

#784 Added mock library for SmmServicesTableLib and mock protocol for SmmCpu
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockSmmServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockSmmCpu.h
  MdePkg/Test/Mock/Library/GoogleTest/MockSmmServicesTableLib/MockSmmServicesTableLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockSmmServicesTableLib/MockSmmServicesTableLib.inf
  MdePkg/Test/Mock/Library/GoogleTest/Protocol/MockSmmCpu.cpp
Labels: impact:non-functional

#786 MdeModulePkg: DxeCore: Use VirtualSize For Image Records
  MdeModulePkg/Core/Dxe/Misc/MemoryAttributesTable.c
  MdeModulePkg/Core/Dxe/Misc/MemoryProtection.c
  MdeModulePkg/Core/Dxe/Misc/MemoryProtectionSupport.c
Labels: impact:security, type:bug

#789 Updated LinuxCFLAGS to match the change made from edk2
  BaseTools/Source/Python/Workspace/DscBuildData.py
Labels: language:python, impact:non-functional, type:bug

#790 [CHERRY-PICK] UefiCpuPkg/MpInitLib: Enable execute disable bit.
  UefiCpuPkg/Library/MpInitLib/MpLib.c
  UefiCpuPkg/Library/MpInitLib/MpLib.h
Labels: type:bug

#791 MdeModulePkg/MemoryProtectionSupport: Fix GCC type mismatch warnings
  MdeModulePkg/Core/Dxe/Misc/MemoryProtectionSupport.c
Labels: impact:non-functional, semver:patch

#793 Add NO_STACK_COOKIE to Module Entry Points
  MdePkg/Include/Library/PeimEntryPoint.h
  MdePkg/Include/Library/StandaloneMmDriverEntryPoint.h
  MdePkg/Include/Library/UefiApplicationEntryPoint.h
  MdePkg/Include/Library/UefiDriverEntryPoint.h
  MdePkg/Library/PeimEntryPoint/PeimEntryPoint.c
  MdePkg/Library/StandaloneMmDriverEntryPoint/StandaloneMmDriverEntryPoint.c
  MdePkg/Library/UefiApplicationEntryPoint/ApplicationEntryPoint.c
  MdePkg/Library/UefiDriverEntryPoint/DriverEntryPoint.c
Labels: impact:security

#796 [CHERRY-PICK] Add NO_STACK_COOKIE to Module Entry Points
  MdePkg/Include/Library/PeimEntryPoint.h
  MdePkg/Include/Library/StandaloneMmDriverEntryPoint.h
  MdePkg/Include/Library/UefiApplicationEntryPoint.h
  MdePkg/Include/Library/UefiDriverEntryPoint.h
  MdePkg/Library/PeimEntryPoint/PeimEntryPoint.c
  MdePkg/Library/StandaloneMmDriverEntryPoint/StandaloneMmDriverEntryPoint.c
  MdePkg/Library/UefiApplicationEntryPoint/ApplicationEntryPoint.c
  MdePkg/Library/UefiDriverEntryPoint/DriverEntryPoint.c
Labels: impact:security

#795 Added mock MmServicesTableLib and mock SmmVarCheck protocol
  MdeModulePkg/Test/Mock/Include/GoogleTest/Protocol/MockSmmVarCheck.h
  MdeModulePkg/Test/Mock/Library/GoogleTest/Protocol/MockSmmVarCheck.cpp
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockMmServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockHash2.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockRng.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockSmmCpu.h
  MdePkg/Test/Mock/Library/GoogleTest/MockMmServicesTableLib/MockMmServicesTableLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockMmServicesTableLib/MockMmServicesTableLib.inf
Labels: impact:non-functional

#799 PixieFail Security Patches for TCBZ451 and TCB4542
  NetworkPkg/Dhcp4Dxe/Dhcp4Driver.c
  NetworkPkg/Dhcp6Dxe/Dhcp6Driver.c
  NetworkPkg/DnsDxe/DnsDhcp.c
  NetworkPkg/DnsDxe/DnsImpl.c
  NetworkPkg/HttpBootDxe/HttpBootDhcp6.c
  NetworkPkg/IScsiDxe/IScsiCHAP.c
  NetworkPkg/IScsiDxe/IScsiMisc.c
  NetworkPkg/IScsiDxe/IScsiMisc.h
  NetworkPkg/Include/Library/NetLib.h
  NetworkPkg/Ip4Dxe/Ip4Driver.c
  NetworkPkg/Ip6Dxe/Ip6ConfigImpl.c
  NetworkPkg/Ip6Dxe/Ip6Driver.c
  NetworkPkg/Ip6Dxe/Ip6If.c
  NetworkPkg/Ip6Dxe/Ip6Mld.c
  NetworkPkg/Ip6Dxe/Ip6Nd.c
  NetworkPkg/Ip6Dxe/Ip6Nd.h
  NetworkPkg/Library/DxeNetLib/DxeNetLib.c
  NetworkPkg/Library/DxeNetLib/DxeNetLib.inf
  NetworkPkg/NetworkPkg.dec
  NetworkPkg/TcpDxe/TcpDriver.c
  NetworkPkg/TcpDxe/TcpDxe.inf
  NetworkPkg/TcpDxe/TcpFunc.h
  NetworkPkg/TcpDxe/TcpInput.c
  NetworkPkg/TcpDxe/TcpMain.h
  NetworkPkg/TcpDxe/TcpMisc.c
  NetworkPkg/TcpDxe/TcpTimer.c
  NetworkPkg/Udp4Dxe/Udp4Driver.c
  NetworkPkg/Udp6Dxe/Udp6Driver.c
  NetworkPkg/UefiPxeBcDxe/PxeBcDhcp4.c
  NetworkPkg/UefiPxeBcDxe/PxeBcDhcp6.c
  NetworkPkg/UefiPxeBcDxe/PxeBcDriver.c
Labels: impact:breaking-change, impact:security, impact:non-functional

#801 [Cherry-Pick] PixieFail Security Patches for TCBZ451 and TCB4542
  NetworkPkg/Dhcp4Dxe/Dhcp4Driver.c
  NetworkPkg/Dhcp6Dxe/Dhcp6Driver.c
  NetworkPkg/DnsDxe/DnsDhcp.c
  NetworkPkg/DnsDxe/DnsImpl.c
  NetworkPkg/HttpBootDxe/HttpBootDhcp6.c
  NetworkPkg/IScsiDxe/IScsiCHAP.c
  NetworkPkg/IScsiDxe/IScsiMisc.c
  NetworkPkg/IScsiDxe/IScsiMisc.h
  NetworkPkg/Include/Library/NetLib.h
  NetworkPkg/Ip4Dxe/Ip4Driver.c
  NetworkPkg/Ip6Dxe/Ip6ConfigImpl.c
  NetworkPkg/Ip6Dxe/Ip6Driver.c
  NetworkPkg/Ip6Dxe/Ip6If.c
  NetworkPkg/Ip6Dxe/Ip6Mld.c
  NetworkPkg/Ip6Dxe/Ip6Nd.c
  NetworkPkg/Ip6Dxe/Ip6Nd.h
  NetworkPkg/Library/DxeNetLib/DxeNetLib.c
  NetworkPkg/Library/DxeNetLib/DxeNetLib.inf
  NetworkPkg/NetworkPkg.dec
  NetworkPkg/TcpDxe/TcpDriver.c
  NetworkPkg/TcpDxe/TcpDxe.inf
  NetworkPkg/TcpDxe/TcpFunc.h
  NetworkPkg/TcpDxe/TcpInput.c
  NetworkPkg/TcpDxe/TcpMain.h
  NetworkPkg/TcpDxe/TcpMisc.c
  NetworkPkg/TcpDxe/TcpTimer.c
  NetworkPkg/Udp4Dxe/Udp4Driver.c
  NetworkPkg/Udp6Dxe/Udp6Driver.c
  NetworkPkg/UefiPxeBcDxe/PxeBcDhcp4.c
  NetworkPkg/UefiPxeBcDxe/PxeBcDhcp6.c
  NetworkPkg/UefiPxeBcDxe/PxeBcDriver.c
Labels: impact:breaking-change, impact:security, impact:non-functional

#794 Map Legacy BIOS Memory RWX When Entering Compatibility Mode
  MdeModulePkg/Core/Dxe/Misc/MemoryProtectionSupport.c
Labels: impact:security

#797 CryptoPkg/BaseCryptLib: add DigestLen to RsaOaepEncrypt(), RsaOaepDecrypt()
  CryptoPkg/Binaries/BaseCryptoDriver_ext_dep.json
  CryptoPkg/Include/Library/BaseCryptLib.h
  CryptoPkg/Include/Protocol/Crypto.h
  CryptoPkg/Library/BaseCryptLibNull/Pk/CryptPkcs1OaepNull.c
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/CryptLib.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/OaepEncryptTests.c
Labels: impact:breaking-change, impact:security, impact:non-functional, impact:testing

#805 CryptoPkg/Binaries: update to 2023.11.3
  CryptoPkg/Binaries/BaseCryptoDriver_ext_dep.json
Labels: impact:security, impact:non-functional, type:documentation

#808 Add ARM and AARCH64 MSCVC Support to StackCheckLib
  MdePkg/Library/StackCheckLib/AArch64/StackCookieInterrupt.S
  MdePkg/Library/StackCheckLib/AArch64/StackCookieInterrupt.asm
  MdePkg/Library/StackCheckLib/Arm/StackCookieInterrupt.asm
  MdePkg/Library/StackCheckLib/StackCheckLibDynamicInit.inf
  MdePkg/Library/StackCheckLib/StackCheckLibStaticInit.inf
Labels: impact:security

#809 .gitattributes: Prevent line ending conversion
  .gitattributes
Labels: impact:non-functional, semver:patch

#806 DscCompleteCheck: Bugfix ignorepaths config option
  .pytool/Plugin/DscCompleteCheck/DscCompleteCheck.py
Labels: impact:non-functional, type:bug

#813 [CHERRY-PICK] MdePkg/SmBios.h: Add New ProcessorFamily definitions for SMBIOS Type4
  MdePkg/Include/IndustryStandard/SmBios.h
Labels: impact:non-functional

#818 Bug: Fix incorrect CodeQL fix - REBASE with PR 6024
  MdeModulePkg/Library/UefiBootManagerLib/BmBoot.c
Labels: type:bug, urgency:high

#823 [Release/202311] Updates NetworkPkg/SecurityFixes.yaml to reflect the current state of CVE patches
  NetworkPkg/SecurityFixes.yaml
Labels: impact:non-functional, type:documentation

#822 Set RO/XP On EfiRuntimeServicesCode Regions Outside of Loaded Image Memory
  MdeModulePkg/Core/Dxe/Misc/MemoryAttributesTable.c
Labels: impact:breaking-change, impact:security

#825 Generate Random Stack Cookie Values in Module Build Path
  BaseTools/Source/Python/build/build.py
Labels: language:python, type:bug

#832 Add EFI Event When Compatibility Mode is Triggered
  MdeModulePkg/Core/Dxe/DxeMain.inf
  MdeModulePkg/Core/Dxe/Misc/MemoryProtectionSupport.c
  MdeModulePkg/Include/Guid/CompatibilityModeActivatedEvent.h
  MdeModulePkg/MdeModulePkg.dec
Labels: type:feature-request

#831 Update Memory Protection Feature Documentation
  Docs/feature_memory_protection.md
Labels: impact:non-functional, type:documentation
