Repository microsoft/mu_basecore, pull requests merged in 2024-03, with the labels that each got.

#757 Update Shared Crypto to version 2023.2.12
  CryptoPkg/Binaries/BaseCryptoDriver_ext_dep.json
Labels: impact:non-functional

#774 [CHERRY-PICK] MdeModulePkg/Bus/Usb/UsbNetwork: Check array index range before access
  MdeModulePkg/Bus/Usb/UsbNetwork/UsbCdcEcm/UsbEcmFunction.c
  MdeModulePkg/Bus/Usb/UsbNetwork/UsbCdcNcm/UsbNcmFunction.c
  MdeModulePkg/Bus/Usb/UsbNetwork/UsbRndis/UsbRndisFunction.c
Labels: impact:non-functional, semver:patch

#771 CryptoPkg/BaseCryptLib: add additional RSAES-OAEP crypto functions
  CryptoPkg/Binaries/BaseCryptoDriver_ext_dep.json
  CryptoPkg/CryptoPkg.dec
  CryptoPkg/Include/Library/BaseCryptLib.h
  CryptoPkg/Include/Protocol/Crypto.h
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/CryptLib.c
Labels: impact:security, impact:non-functional, impact:testing

#776 BmpCheckPlugin: Pass build vars to FDF parser
  BaseTools/Plugin/BmpCheck/BmpCheckPlugin.py
Labels: language:python, impact:non-functional, type:bug

#777 CryptoPkg: Update shared crypto to 2023.11.2
  CryptoPkg/Binaries/BaseCryptoDriver_ext_dep.json
Labels: impact:security, impact:non-functional, semver:patch

#780 Added Mock GoogleTest folder for PolicyLibCommon
  PolicyServicePkg/PolicyServicePkg.dec
  PolicyServicePkg/Test/Mock/Include/GoogleTest/Library/MockPolicyLibCommon.h
  PolicyServicePkg/Test/Mock/Library/GoogleTest/MockPolicyLibCommon/MockPolicyLibCommon.cpp
  PolicyServicePkg/Test/Mock/Library/GoogleTest/MockPolicyLibCommon/MockPolicyLibCommon.inf
  PolicyServicePkg/Test/PolicyServicePkgHostTest.dsc
Labels: impact:non-functional

#773 Rework Buildtime Random Stack Cookie Values to Improve Incremental Build Times and Ensure Binary Reproducibility
  BaseTools/Source/Python/AutoGen/GenC.py
  BaseTools/Source/Python/Common/GlobalData.py
  BaseTools/Source/Python/build/build.py
Labels: type:enhancement, language:python, impact:security, type:design-change, type:bug

#781 [CHERRY-PICK] Rework Buildtime Random Stack Cookie Values
  BaseTools/Source/Python/AutoGen/GenC.py
  BaseTools/Source/Python/Common/GlobalData.py
  BaseTools/Source/Python/build/build.py
Labels: type:enhancement, language:python, impact:security, type:design-change, type:bug
