Repository microsoft/mu_basecore, pull requests merged in 2024-10, with the labels that each got.

#1166 [SQUASH ON REBASE] Fix naming convention in FirmwareVolume2 gmock
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockFirmwareVolume2.h
Labels: impact:non-functional, impact:testing

#1175 [CHERRY-PICK] MdeModulePkg: Gcd: Only Update gMemoryMap Attributes if Correct GCD Type
  MdeModulePkg/Core/Dxe/Gcd/Gcd.c
Labels: impact:non-functional

#1178 MdePkg: Add Gmock for PcdLib
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockPcdLib.h
  MdePkg/Test/Mock/Library/GoogleTest/MockPcdLib/MockPcdLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockPcdLib/MockPcdLib.inf
Labels: impact:non-functional

#1179 [Rebase & FF] MdePkg: Add gmock for PcdLib
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockPcdLib.h
  MdePkg/Test/Mock/Library/GoogleTest/MockPcdLib/MockPcdLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockPcdLib/MockPcdLib.inf
Labels: impact:non-functional

#1187 [Rebase & FF] Fix PI status code
  MdePkg/Include/Pi/PiStatusCode.h
Labels: impact:breaking-change, impact:non-functional

#1182 [REBASE & FF]: Bring in more mocks from release/202311
  MdeModulePkg/Test/MdeModulePkgHostTest.dsc
  MdeModulePkg/Test/Mock/Include/GoogleTest/Library/MockCapsuleLib.h
  MdeModulePkg/Test/Mock/Include/GoogleTest/Library/MockUefiBootManagerLib.h
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockCapsuleLib/MockCapsuleLib.cpp
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockCapsuleLib/MockCapsuleLib.inf
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockUefiBootManagerLib/MockUefiBootManagerLib.cpp
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockUefiBootManagerLib/MockUefiBootManagerLib.inf
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockPerformanceLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockGenericMemoryTest.h
  MdePkg/Test/Mock/Library/GoogleTest/MockPerformanceLib/MockPerformanceLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockPerformanceLib/MockPerformanceLib.inf
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiLib/MockUefiLib.cpp
Labels: impact:non-functional

#1188 [Cherry-Pick] MdePkg: Add Gmock libraries
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockCpuLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockPciSegmentLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockReportStatusCodeLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockSmmServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockMpService.h
  MdePkg/Test/Mock/Library/GoogleTest/MockCpuLib/MockCpuLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockCpuLib/MockCpuLib.inf
  MdePkg/Test/Mock/Library/GoogleTest/MockPciSegmentLib/MockPciSegmentLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockPciSegmentLib/MockPciSegmentLib.inf
  MdePkg/Test/Mock/Library/GoogleTest/MockReportStatusCodeLib/MockReportStatusCodeLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockReportStatusCodeLib/MockReportStatusCodeLib.inf
  MdePkg/Test/Mock/Library/GoogleTest/MockSmmServicesTableLib/MockSmmServicesTableLib.cpp
Labels: impact:non-functional

#1189 [Cherry-Pick] MdePkg: Add Gmocks for libraries
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockCpuLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockPciSegmentLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockReportStatusCodeLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockSmmServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockMpService.h
  MdePkg/Test/Mock/Library/GoogleTest/MockCpuLib/MockCpuLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockCpuLib/MockCpuLib.inf
  MdePkg/Test/Mock/Library/GoogleTest/MockPciSegmentLib/MockPciSegmentLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockPciSegmentLib/MockPciSegmentLib.inf
  MdePkg/Test/Mock/Library/GoogleTest/MockReportStatusCodeLib/MockReportStatusCodeLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockReportStatusCodeLib/MockReportStatusCodeLib.inf
  MdePkg/Test/Mock/Library/GoogleTest/MockSmmServicesTableLib/MockSmmServicesTableLib.cpp
Labels: impact:non-functional

#1190 [SQUASH ON REBASE] Move inline comments to separate lines for tools_def
  BaseTools/Conf/tools_def.template
Labels: type:bug

#1195 Added missing fix for ProductDataFormatter missed from 202311
  BaseTools/Source/Python/ProductDataFormatter/ProductDataFormatter.py
Labels: language:python, impact:non-functional, type:bug

#1177 Declare mock SMM Access2 Protocol.
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockSmmAccess2.h
Labels: impact:non-functional, impact:testing

#1196 [CHERRY-PICK] Added missing fix for ProductDataFormatter missed from 202311 (#1195)
  BaseTools/Source/Python/ProductDataFormatter/ProductDataFormatter.py
Labels: language:python, impact:non-functional

#1197 [CHERRY-PICK] Bring in more mocks from release/202311
  MdeModulePkg/Test/MdeModulePkgHostTest.dsc
  MdeModulePkg/Test/Mock/Include/GoogleTest/Library/MockCapsuleLib.h
  MdeModulePkg/Test/Mock/Include/GoogleTest/Library/MockUefiBootManagerLib.h
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockCapsuleLib/MockCapsuleLib.cpp
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockCapsuleLib/MockCapsuleLib.inf
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockUefiBootManagerLib/MockUefiBootManagerLib.cpp
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockUefiBootManagerLib/MockUefiBootManagerLib.inf
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockPerformanceLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockGenericMemoryTest.h
  MdePkg/Test/Mock/Library/GoogleTest/MockPerformanceLib/MockPerformanceLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockPerformanceLib/MockPerformanceLib.inf
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiLib/MockUefiLib.cpp
Labels: impact:non-functional

#1176 MdePkg MockUefiLib: Add new mock functions.
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiLib.h
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiLib/MockUefiLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiLib/MockUefiLib.inf
Labels: impact:non-functional

#1198 [Cherry-Pick] StandaloneMmPkg: Initialize 'WillReturn' variable
  StandaloneMmPkg/Core/Mmi.c
Labels: impact:non-functional

#1201 Add release branch backport workflow
  .github/pull_request_template.md
  .github/workflows/backport-to-release-branch.yml
  .github/workflows/label-issues/regex-pull-requests.yml
Labels: impact:non-functional, type:feature-request

#1200 [Cherry-Pick] StandaloneMmPkg: Initialize 'WillReturn' variable
  StandaloneMmPkg/Core/Mmi.c
Labels: impact:non-functional

#1199 [CHERRY-PICK] .pytool/UncrustifyCheck: Show errors in output
  .pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py
Labels: type:enhancement, impact:non-functional, type:backport

#1150 Add Line Ending plugin
  .pytool/Plugin/LineEndingCheck/LineEndingCheck.py
  .pytool/Plugin/LineEndingCheck/Readme.md
  .pytool/Plugin/LineEndingCheck/line_ending_check_plug_in.yaml
  .pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py
  BaseTools/Plugin/BmpCheck/BmpCheckPlugin.py
  BaseTools/Plugin/Edk2ToolHelper/Edk2ToolHelper.py
  BaseTools/Plugin/Sample/HelloWorld.py
  BaseTools/Plugin/WindowsCapsuleSupportHelper/WindowsCapsuleSupportHelper.py
  BaseTools/Scripts/GenFmpImageAuth.py
  BaseTools/Scripts/WindowsCapsuleFileGen.py
  MdeModulePkg/Library/BaseExceptionPersistenceLibNull/BaseExceptionPersistenceLibNull.inf
  MdeModulePkg/Library/CapsulePersistLibNull/CapsulePersistLibNull.inf
  MdeModulePkg/Library/DeviceStateLib/DeviceStateLib.inf
  MdeModulePkg/Library/DeviceStateLib/Readme.md
  MdeModulePkg/Library/MemoryProtectionHobLib/DxeMemoryProtectionHobLib.inf
  MdeModulePkg/Library/MemoryProtectionHobLib/SmmMemoryProtectionHobLib.inf
  MdeModulePkg/Library/MemoryProtectionHobLib/StandaloneMmMemoryProtectionHobLib.inf
  MdeModulePkg/Library/MemoryProtectionHobLibNull/DxeMemoryProtectionHobLibNull.inf
  MdeModulePkg/Library/MemoryProtectionHobLibNull/MmMemoryProtectionHobLibNull.inf
  MdeModulePkg/Library/MemoryTypeInfoSecVarCheckLib/MemoryTypeInfoSecVarCheckLib.inf
  MdeModulePkg/Library/MemoryTypeInformationChangeLibNull/MemoryTypeInformationChangeLibNull.inf
  MdeModulePkg/Library/ParallelLzmaCustomDecompressLib/ParallelLzmaCustomDecompressLib.inf
  MdeModulePkg/Library/SecurityLockAuditDebugMessageLib/SecurityLockAuditDebugMessageLib.inf
  MdeModulePkg/Library/SecurityLockAuditLibNull/SecurityLockAuditLibNull.inf
  MdeModulePkg/Library/VarCheckPolicyLib/VarCheckPolicyLibVariableDxe.inf
  MdeModulePkg/Library/VariablePolicyLib/VariablePolicyUnitTest/VariablePolicyUnitTest.inf
  MdeModulePkg/Test/ShellTest/VariablePolicyFuncTestApp/Readme.md
  MdeModulePkg/Test/ShellTest/VariablePolicyFuncTestApp/VariablePolicyFuncTestApp.inf
  MdeModulePkg/Universal/Variable/RuntimeDxe/RuntimeDxeUnitTest/VariableRuntimeDxeUnitTest.inf
  MdePkg/Library/BaseLib/AArch64/CpuBreakAssert.S
  MdePkg/Library/BaseMmuLibNull/BaseMmuLibNull.inf
  MdePkg/Library/CompilerIntrinsicsLib/ArmCompilerIntrinsicsLib.inf
  MdePkg/Library/FltUsedLib/FltUsedLib.inf
  MdePkg/Library/FltUsedLib/Readme.md
  MdePkg/Library/VsIntrinsicLib/IA32/llmul.asm
  MdePkg/Library/VsIntrinsicLib/VsIntrinsicLib.inf
  MdePkg/Library/VsIntrinsicLib/VsIntrinsicLib.uni
  MdePkg/Test/Library/RngLibHostTestLfsr/RngLibHostTestLfsr.inf
  MdePkg/Test/Mock/Library/Stub/StubUefiLib/StubUefiLib.inf
  PolicyServicePkg/CommonPolicy/Template_PolicyHeader.yaml
  PolicyServicePkg/Plugins/UpdatePolicyHdr/UpdatePolicyHdr.py
  PolicyServicePkg/Samples/PolicyDefinitions/GFX_policy_def.yaml
  PolicyServicePkg/Tools/GenCfgData.py
  ShellPkg/Application/ShellCTestApp/TestArgv.log
  StandaloneMmPkg/Library/StandaloneMmCoreEntryPointNull/StandaloneMmCoreEntryPointNull.inf
Labels: language:python, impact:non-functional, type:backport
