Repository microsoft/mu_basecore, pull requests merged in 2024-12, with the labels that each got.

#1236 [CHERRY-PICK] MdePkg/SmBios.h: Add new Processor Upgrade definition for SMBIOS Type4 and Updated Type 4 Info as per Smbios 3.8.0
  MdePkg/Include/IndustryStandard/SmBios.h
Labels: impact:non-functional, type:backport

#1237 [CHERRY-PICK] MdePkg/SmBios.h: Add new Processor Upgrade definition for SMBIOS Type4 and Updated Type 4 Info as per Smbios 3.8.0
  MdePkg/Include/IndustryStandard/SmBios.h
Labels: impact:non-functional

#1241 [SQUASH ON REBASE] Remove Windows ARM BaseTools Build
  .azurepipelines/BaseTools-Build-For-Publication.yml
Labels: impact:breaking-change, impact:non-functional, type:backport

#1238 Add MockVariablePolicyHelperLib
  MdeModulePkg/Test/MdeModulePkgHostTest.dsc
  MdeModulePkg/Test/Mock/Include/GoogleTest/Library/MockVariablePolicyHelperLib.h
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockVariablePolicyHelperLib/MockVariablePolicyHelperLib.cpp
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockVariablePolicyHelperLib/MockVariablePolicyHelperLib.inf
Labels: impact:non-functional, impact:testing, type:backport

#1242 [SQUASH ON REBASE] Remove Windows ARM BaseTools Build
  .github/workflows/release-basetools.yml
Labels: impact:non-functional, type:backport

#1240 [SQUASH ON REBASE] Move inline comments to separate lines for tools_def
  BaseTools/Conf/tools_def.template
Labels: type:bug

#1216 Add mock for protocol MockFirmwareVolumeBlock under MdePkg
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockFirmwareVolumeBlock.h
Labels: impact:non-functional, type:backport

#1235 Create Mock for SafeIntLib
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockSafeIntLib.h
  MdePkg/Test/Mock/Library/GoogleTest/MockSafeIntLib/MockSafeIntLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockSafeIntLib/MockSafeIntLib.inf
Labels: impact:non-functional, type:backport

#1245 Update shared crypto to v1.0.0
  CryptoPkg/Binaries/BaseCryptoDriver_ext_dep.json
Labels: impact:breaking-change, type:backport

#1243 BaseTools: Disable Second DLINK step for WHOLEARCHIVE
  BaseTools/Conf/build_rule.template
Labels: impact:non-functional, type:backport

#1213 Createa Mock for PciRootBridgeIoProtocol, MockPciPlatformProtocol & add mock function under MockUefiBootServiceTableLib
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiBootServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockPciPlatformProtocol.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockPciRootBridgeIoProtocol.h
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiBootServicesTableLib/MockUefiBootServicesTableLib.cpp
Labels: impact:non-functional, type:backport

#1247 Update shared crypto to v1.0.1
  CryptoPkg/Binaries/BaseCryptoDriver_ext_dep.json
Labels: impact:non-functional, type:backport
