Repository microsoft/mu_basecore, pull requests merged in 2024-02, with the labels that each got.

#715 CryptoPkg: Update shared crypto to 2023.2.8
  CryptoPkg/Driver/Bin/BaseCryptoDriver_ext_dep.json
Labels: impact:security, semver:patch

#716 [CHERRY-PICK] Support building BaseLib for AARCH64 with VC on 202311 (#662)
  MdePkg/Library/BaseLib/AArch64/SetJumpLongJump.asm
  MdePkg/Library/BaseLib/Arm/SetJumpLongJump.asm
Labels: impact:non-functional

#709 Add SHA384 and SHA512 to the STANDARD flavor of the crypto binary
  CryptoPkg/Driver/Bin/Crypto.pcd.STANDARD.inc.dsc
  CryptoPkg/Driver/Packaging/generate_cryptodriver.py
Labels: language:python

#719 [CHERRY-PICK] Repo File Sync: Add permissions to GitHub workflows
  .azurepipelines/MuDevOpsWrapper.yml
  .github/workflows/auto-approve.yml
  .github/workflows/auto-merge.yml
  .github/workflows/issue-assignment.yml
  .github/workflows/label-issues.yml
  .github/workflows/label-sync.yml
  .github/workflows/pull-request-formatting-validator.yml
  .github/workflows/release-draft.yml
  .github/workflows/scheduled-maintenance.yml
  .github/workflows/stale.yml
  .github/workflows/triage-issues.yml
Labels: semver:patch

#718 release-basetools.yml: Add contents write permission for publishing
  .github/workflows/release-basetools.yml
Labels: semver:patch

#717 [CHERRY-PICK] release-basetools.yml: Add contents write permission for publishing
  .github/workflows/release-basetools.yml
Labels: impact:non-functional, semver:patch

#720 [CHERRY-PICK] CryptoPkg: Update shared crypto to 2023.2.8
  CryptoPkg/Driver/Bin/BaseCryptoDriver_ext_dep.json
Labels: impact:security, semver:patch

#722 [CHERRY-PICK] Add SHA384 and SHA512 to the STANDARD flavor of the crypto binary
  CryptoPkg/Driver/Bin/Crypto.pcd.STANDARD.inc.dsc
  CryptoPkg/Driver/Packaging/generate_cryptodriver.py
Labels: language:python, impact:non-functional

#712 Restore IntrinsicLib to CryptoPkg
  CryptoPkg/CryptoPkg.dsc
  CryptoPkg/Library/IntrinsicLib/BaseIntrinsicLib.uni
  CryptoPkg/Library/IntrinsicLib/CopyMem.c
  CryptoPkg/Library/IntrinsicLib/Ia32/MathDivModU64x64.c
  CryptoPkg/Library/IntrinsicLib/Ia32/MathDivS64x64.c
  CryptoPkg/Library/IntrinsicLib/Ia32/MathDivU64x64.c
  CryptoPkg/Library/IntrinsicLib/Ia32/MathFtol.c
  CryptoPkg/Library/IntrinsicLib/Ia32/MathLShiftS64.c
  CryptoPkg/Library/IntrinsicLib/Ia32/MathLShiftS64.nasm
  CryptoPkg/Library/IntrinsicLib/Ia32/MathLldiv.asm
  CryptoPkg/Library/IntrinsicLib/Ia32/MathLlmul.asm
  CryptoPkg/Library/IntrinsicLib/Ia32/MathLlshr.asm
  CryptoPkg/Library/IntrinsicLib/Ia32/MathModU64x64.c
  CryptoPkg/Library/IntrinsicLib/Ia32/MathRShiftU64.c
  CryptoPkg/Library/IntrinsicLib/Ia32/MathRShiftU64.nasm
  CryptoPkg/Library/IntrinsicLib/Ia32/MathUlldiv.asm
  CryptoPkg/Library/IntrinsicLib/Ia32/MathUlldvrm.asm
  CryptoPkg/Library/IntrinsicLib/Ia32/MathUllrem.asm
  CryptoPkg/Library/IntrinsicLib/IntrinsicLib.inf
  CryptoPkg/Library/IntrinsicLib/MemoryIntrinsics.c
Labels: impact:non-functional

#731 CryptoPkg: Add RT DXE shared crypto library instance
  CryptoPkg/CryptoPkg.dsc
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/RuntimeDxeCryptLib.c
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/RuntimeDxeCryptLib.inf
Labels: type:enhancement

#735 [CHERRY-PICK] Restore IntrinsicLib to CryptoPkg
  CryptoPkg/CryptoPkg.dsc
  CryptoPkg/Library/IntrinsicLib/BaseIntrinsicLib.uni
  CryptoPkg/Library/IntrinsicLib/CopyMem.c
  CryptoPkg/Library/IntrinsicLib/Ia32/MathDivModU64x64.c
  CryptoPkg/Library/IntrinsicLib/Ia32/MathDivS64x64.c
  CryptoPkg/Library/IntrinsicLib/Ia32/MathDivU64x64.c
  CryptoPkg/Library/IntrinsicLib/Ia32/MathFtol.c
  CryptoPkg/Library/IntrinsicLib/Ia32/MathLShiftS64.c
  CryptoPkg/Library/IntrinsicLib/Ia32/MathLShiftS64.nasm
  CryptoPkg/Library/IntrinsicLib/Ia32/MathLldiv.asm
  CryptoPkg/Library/IntrinsicLib/Ia32/MathLlmul.asm
  CryptoPkg/Library/IntrinsicLib/Ia32/MathLlshr.asm
  CryptoPkg/Library/IntrinsicLib/Ia32/MathModU64x64.c
  CryptoPkg/Library/IntrinsicLib/Ia32/MathRShiftU64.c
  CryptoPkg/Library/IntrinsicLib/Ia32/MathRShiftU64.nasm
  CryptoPkg/Library/IntrinsicLib/Ia32/MathUlldiv.asm
  CryptoPkg/Library/IntrinsicLib/Ia32/MathUlldvrm.asm
  CryptoPkg/Library/IntrinsicLib/Ia32/MathUllrem.asm
  CryptoPkg/Library/IntrinsicLib/IntrinsicLib.inf
  CryptoPkg/Library/IntrinsicLib/MemoryIntrinsics.c
Labels: impact:non-functional

#736 .pytool/Plugin/DscCompleteCheck: Allow git ignore syntax
  .pytool/Plugin/DscCompleteCheck/DscCompleteCheck.py
  .pytool/Plugin/DscCompleteCheck/Readme.md
Labels: type:enhancement, type:documentation

#740 BaseTools/GenFds: Resolve absolute workspace INF paths
  BaseTools/Source/Python/GenFds/FfsInfStatement.py
Labels: language:python, semver:patch

#741 CryptoPkg/RuntimeDxeCryptLib: Make globals static
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/RuntimeDxeCryptLib.c
Labels: impact:non-functional, semver:patch

#739 [Release/202302] Cherry-Picks PixieFail vulnerability fixes for Bugs 1-7
  NetworkPkg/Dhcp6Dxe/Dhcp6Impl.h
  NetworkPkg/Dhcp6Dxe/Dhcp6Io.c
  NetworkPkg/Dhcp6Dxe/Dhcp6Io.h
  NetworkPkg/Dhcp6Dxe/Dhcp6Utility.c
  NetworkPkg/Dhcp6Dxe/Dhcp6Utility.h
  NetworkPkg/Dhcp6Dxe/GoogleTest/Dhcp6DxeGoogleTest.cpp
  NetworkPkg/Dhcp6Dxe/GoogleTest/Dhcp6DxeGoogleTest.inf
  NetworkPkg/Dhcp6Dxe/GoogleTest/Dhcp6IoGoogleTest.cpp
  NetworkPkg/Dhcp6Dxe/GoogleTest/Dhcp6IoGoogleTest.h
  NetworkPkg/Ip6Dxe/GoogleTest/Ip6DxeGoogleTest.cpp
  NetworkPkg/Ip6Dxe/GoogleTest/Ip6DxeGoogleTest.inf
  NetworkPkg/Ip6Dxe/GoogleTest/Ip6OptionGoogleTest.cpp
  NetworkPkg/Ip6Dxe/GoogleTest/Ip6OptionGoogleTest.h
  NetworkPkg/Ip6Dxe/Ip6Nd.h
  NetworkPkg/Ip6Dxe/Ip6Option.c
  NetworkPkg/Ip6Dxe/Ip6Option.h
  NetworkPkg/NetworkPkg.ci.yaml
  NetworkPkg/SecurityFixes.yaml
  NetworkPkg/Test/NetworkPkgHostTest.dsc
  NetworkPkg/UefiPxeBcDxe/GoogleTest/PxeBcDhcp6GoogleTest.cpp
  NetworkPkg/UefiPxeBcDxe/GoogleTest/PxeBcDhcp6GoogleTest.h
  NetworkPkg/UefiPxeBcDxe/GoogleTest/UefiPxeBcDxeGoogleTest.cpp
  NetworkPkg/UefiPxeBcDxe/GoogleTest/UefiPxeBcDxeGoogleTest.inf
  NetworkPkg/UefiPxeBcDxe/PxeBcDhcp6.c
  NetworkPkg/UefiPxeBcDxe/PxeBcDhcp6.h
Labels: impact:security, impact:non-functional, type:documentation, impact:testing

#738 [Release/202311] Cherry-Picks PixieFail vulnerability fixes for Bugs 1-7
  NetworkPkg/Dhcp6Dxe/Dhcp6Impl.h
  NetworkPkg/Dhcp6Dxe/Dhcp6Io.c
  NetworkPkg/Dhcp6Dxe/Dhcp6Io.h
  NetworkPkg/Dhcp6Dxe/Dhcp6Utility.c
  NetworkPkg/Dhcp6Dxe/Dhcp6Utility.h
  NetworkPkg/Dhcp6Dxe/GoogleTest/Dhcp6DxeGoogleTest.cpp
  NetworkPkg/Dhcp6Dxe/GoogleTest/Dhcp6DxeGoogleTest.inf
  NetworkPkg/Dhcp6Dxe/GoogleTest/Dhcp6IoGoogleTest.cpp
  NetworkPkg/Dhcp6Dxe/GoogleTest/Dhcp6IoGoogleTest.h
  NetworkPkg/Ip6Dxe/GoogleTest/Ip6DxeGoogleTest.cpp
  NetworkPkg/Ip6Dxe/GoogleTest/Ip6DxeGoogleTest.inf
  NetworkPkg/Ip6Dxe/GoogleTest/Ip6OptionGoogleTest.cpp
  NetworkPkg/Ip6Dxe/GoogleTest/Ip6OptionGoogleTest.h
  NetworkPkg/Ip6Dxe/Ip6Nd.h
  NetworkPkg/Ip6Dxe/Ip6Option.c
  NetworkPkg/Ip6Dxe/Ip6Option.h
  NetworkPkg/NetworkPkg.ci.yaml
  NetworkPkg/SecurityFixes.yaml
  NetworkPkg/Test/NetworkPkgHostTest.dsc
  NetworkPkg/UefiPxeBcDxe/GoogleTest/PxeBcDhcp6GoogleTest.cpp
  NetworkPkg/UefiPxeBcDxe/GoogleTest/PxeBcDhcp6GoogleTest.h
  NetworkPkg/UefiPxeBcDxe/GoogleTest/UefiPxeBcDxeGoogleTest.cpp
  NetworkPkg/UefiPxeBcDxe/GoogleTest/UefiPxeBcDxeGoogleTest.inf
  NetworkPkg/UefiPxeBcDxe/PxeBcDhcp6.c
  NetworkPkg/UefiPxeBcDxe/PxeBcDhcp6.h
Labels: impact:security, impact:non-functional, type:documentation, impact:testing

#737 RustEnvironmentCheck: Check Version if specified
  BaseTools/Plugin/RustEnvironmentCheck/RustEnvironmentCheck.py
Labels: language:python, impact:non-functional

#732 remove edk2-basetools
  .pytool/CISettings.py
  UefiCpuPkg/UefiCpuPkg.dsc
  pip-requirements.txt
Labels: impact:non-functional

#746 BaseTools/RustEnvironmentCheck: Allow no tools in toolchain file
  BaseTools/Plugin/RustEnvironmentCheck/RustEnvironmentCheck.py
Labels: language:python, type:bug

#745 Edk2ToolsBuild: override basetoolsbin_ext_dep
  BaseTools/Bin/basetoolsbin_ext_dep.yaml
  BaseTools/Edk2ToolsBuild.py
Labels: type:enhancement, language:python, impact:non-functional

#749 RustEnvironmentCheck: Bugfix embedded quotes
  BaseTools/Plugin/RustEnvironmentCheck/RustEnvironmentCheck.py
Labels: language:python, impact:non-functional

#747 ImageValidation: Pass build vars to fdf parser
  .pytool/Plugin/ImageValidation/ImageValidation.py
Labels: impact:non-functional

#751 CryptoPkg: Update to Shared Crypto 2023.2.11
  CryptoPkg/Binaries/BaseCryptoDriver_ext_dep.json
Labels: impact:non-functional, semver:patch

#744 [Cherry-Pick]: UefiCpuPkg/CpuMpPei. Use CpuPageTableLib to set memory attribute. Parallel get stack base for better performance.
  UefiCpuPkg/CpuMpPei/CpuPaging.c
Labels: impact:breaking-change, impact:non-functional

#743 Codeql update from 2.15.4 to 2.16.1
  BaseTools/Plugin/CodeQL/codeqlcli_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_linux_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_windows_ext_dep.yaml
Labels: impact:non-functional
