Repository microsoft/mu_basecore, pull requests merged in 2025-07, with the labels that each got.

#1418 Replace SMCCC_VERSION check with FF-A version check
  MdeModulePkg/Library/ArmFfaLib/ArmFfaCommon.c
Labels: type:bug, type:backport

#1421 codeql: Use app token for API requests
  .github/workflows/codeql.yml
Labels: impact:non-functional

#1422 [CHERRY-PICK] MdePkg: Updated Memory Form Factor definition per SMBIOS 3.8.0
  MdePkg/Include/IndustryStandard/SmBios.h
Labels: impact:non-functional, type:backport

#1429 Update memory map descriptor merging logic to honor the bucket type information
  MdeModulePkg/Core/Dxe/Mem/Imem.h
  MdeModulePkg/Core/Dxe/Mem/Page.c
  MdeModulePkg/Core/Dxe/Misc/MemoryProtectionSupport.c
  MdeModulePkg/Core/Dxe/Misc/MemoryProtectionSupport.h
Labels: type:bug, type:backport

#1435 [CHERRY-PICK] MdePkg: Add DEBUG_SECURITY Bit in PcdDebugPrintErrorLevel
  MdePkg/Include/Library/DebugLib.h
  MdePkg/MdePkg.dec
Labels: impact:non-functional, type:backport

#1437 [SQUASH ON REBASE] Fix bucket type matching as soon as the bucket is ready
  MdeModulePkg/Core/Dxe/Mem/Page.c
Labels: type:bug, type:backport
