Repository microsoft/mu_basecore, pull requests merged in 2025-08, with the labels that each got.

#1457 [CHERRY-PICK] UefiCpuPkg/PiSmmCpuDxeSmm: Safe handling of IDT register on SMM entry
  UefiCpuPkg/PiSmmCpuDxeSmm/X64/SmiEntry.nasm
Labels: impact:security, impact:non-functional, type:backport

#1459 [CHERRY-PICK] UefiCpuPkg/PiSmmCpuDxeSmm: Safe handling of IDT register on SMM entry
  UefiCpuPkg/PiSmmCpuDxeSmm/X64/SmiEntry.nasm
Labels: impact:security, impact:non-functional

#1460 [CHERRY-PICK] UefiCpuPkg/PiSmmCpuDxeSmm: Safe handling of IDT register on SMM entry
  UefiCpuPkg/PiSmmCpuDxeSmm/X64/SmiEntry.nasm
Labels: impact:security, impact:non-functional

#1454 MdeModulePkg: Fix CoherentPciIoUnmap
  MdeModulePkg/Bus/Pci/NonDiscoverablePciDeviceDxe/NonDiscoverablePciDeviceIo.c
Labels: type:backport

#1465 [Rebase & FF] MdePkg: TpmPtp: Add CRB Interface Version 2 Definition
  MdePkg/Include/IndustryStandard/TpmPtp.h
Labels: impact:non-functional, type:backport

#1471 Revert "[dev/202502] Update BaseTools ext dep to dev-v2025020001.0.3 (#1467)"
  BaseTools/Bin/basetoolsbin_ext_dep.yaml
Labels: impact:non-functional

#1469 [202405] pip-requirements.txt: Update edk2-pytools to latest
  pip-requirements.txt
Labels: impact:non-functional, type:backport

#1475 build_rule.template: Update version to 3.00
  BaseTools/Conf/build_rule.template
Labels: impact:non-functional, type:backport

#1476 BaseTools: Fix extdep for base tool binaries
  BaseTools/Bin/basetoolsbin_ext_dep.yaml
Labels: impact:non-functional

#1486 MdeModulePkg/PiSmmIpl: Prevent freeing from uninitialized pointers
  MdeModulePkg/Core/PiSmmCore/PiSmmIpl.c
Labels: impact:non-functional, type:bug, type:backport
