Repository microsoft/mu_basecore, pull requests merged in 2025-05, with the labels that each got.

#1350 FileSync: bring githhub app backport to 202405
  .github/workflows/backport-to-release-branch.yml
  .github/workflows/release-basetools.yml
Labels: impact:non-functional, type:backport

#1353 Minor Plugin Tweaks
  .pytool/Plugin/DependencyCheck/DependencyCheck.py
  .pytool/Plugin/GuidCheck/GuidCheck.py
  .pytool/Plugin/HostUnitTestDscCompleteCheck/HostUnitTestDscCompleteCheck.py
  .pytool/Plugin/LibraryClassCheck/LibraryClassCheck.py
  .pytool/Plugin/SpellCheck/SpellCheck.py
Labels: impact:non-functional, type:backport

#1340 MdePkg: Add MockSynchronizationLib and MockSmmSxDispatch2
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockSynchronizationLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockSmmSxDispatch2.h
  MdePkg/Test/Mock/Library/GoogleTest/MockSynchronizationLib/MockSynchronizationLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockSynchronizationLib/MockSynchronizationLib.inf
Labels: impact:non-functional, impact:testing, type:backport

#1355 Add X509CompareDateTime Function
  CryptoPkg/CryptoPkg.dec
  CryptoPkg/Include/Protocol/Crypto.h
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/CryptLib.c
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/DxeCryptLib.inf
Labels: type:backport

#1361 MdePkg: Add MockSynchronizationLib and MockSmmSxDispatch2 [Merge & FF]
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockSynchronizationLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockSmmSxDispatch2.h
  MdePkg/Test/Mock/Library/GoogleTest/MockSynchronizationLib/MockSynchronizationLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockSynchronizationLib/MockSynchronizationLib.inf
Labels: impact:non-functional

#1363 Revert TpmLogProtocol Changes
  MdePkg/Include/IndustryStandard/UefiTcgPlatform.h
  MdePkg/Include/Protocol/Tcg2Protocol.h
  MdePkg/Include/Protocol/TpmLogProtocol.h
  MdePkg/MdePkg.dec
Labels: impact:breaking-change, impact:non-functional

#1368 Update Basetools
  BaseTools/Bin/basetoolsbin_ext_dep.yaml
Labels: type:backport

#1376 NVME: Fix an issue with zero-sized queue allocation
  MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressHci.c
Labels: type:bug, type:backport

#1370 MdeModulePkg/FaultTolerantWriteDxe: Add validation for FtwWorkSpaceHeader
  MdeModulePkg/Universal/FaultTolerantWriteDxe/FtwMisc.c
  MdeModulePkg/Universal/FaultTolerantWriteDxe/UpdateWorkingBlock.c
Labels: type:backport

#1378 [SQUASH ON REBASE] MdeModulePkg: Fix macros to convert bytes to pages
  MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpress.h
Labels: type:bug, type:backport

#1389 Fix the release sha256 after modifying the release
  BaseTools/Bin/basetoolsbin_ext_dep.yaml
Labels: impact:non-functional, urgency:high, type:backport

#1386 [CHERRY-PICK] NetworkPkg: Update to make IPv6 prefix length 128 will not be excluded
  NetworkPkg/Ip6Dxe/Ip6Icmp.c
  NetworkPkg/Library/DxeNetLib/DxeNetLib.c
Labels: type:backport
