Repository microsoft/mu_basecore, pull requests merged in 2025-03, with the labels that each got.

#1296 [CHERRY-PICK] DebugMacroCheck: Do not show progress bar with zero items
  BaseTools/Plugin/DebugMacroCheck/DebugMacroCheck.py
Labels: language:python, type:bug, type:backport

#1288 MdePkg: Add Google Mock Protocol for MmCommunication2
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockMmCommunication2.h
Labels: impact:non-functional, type:backport

#1279 MdePkg: Add all mock functions in the MockMmServicesTableLib
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockMmServicesTableLib.h
  MdePkg/Test/Mock/Library/GoogleTest/MockMmServicesTableLib/MockMmServicesTableLib.cpp
Labels: impact:non-functional, type:backport

#1293 [SQUASH_ON_REBASE] Remove unused variable in DEBUG_CLEAR_MEMORY call
  UnitTestFrameworkPkg/Library/Posix/MemoryAllocationLibPosix/MemoryAllocationLibPosix.c
Labels: impact:non-functional

#1301 Temporarly remove VariableRuntimeDxeUnitTest from running in GCC
  MdeModulePkg/MdeModulePkg.ci.yaml
  MdeModulePkg/Test/MdeModulePkgHostTest.dsc
Labels: impact:non-functional

#1287 StandaloneMmPkg: Add Google Mock Library for StandaloneMmMemLib
  StandaloneMmPkg/StandaloneMmPkg.dec
  StandaloneMmPkg/Test/Mock/Include/GoogleTest/Library/MockStandaloneMmMemLib.h
  StandaloneMmPkg/Test/Mock/Library/GoogleTest/MockStandaloneMmMemLib/MockStandaloneMmMemLib.cpp
  StandaloneMmPkg/Test/Mock/Library/GoogleTest/MockStandaloneMmMemLib/MockStandaloneMmMemLib.inf
Labels: impact:non-functional, type:backport

#1304 Complete MockBootServicesTableLib.cpp
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiBootServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockSimpleTextIn.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockSimpleTextOut.h
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiBootServicesTableLib/MockUefiBootServicesTableLib.cpp
Labels: impact:non-functional, type:backport

#1310 WindowsVsToolChain: Filter vs vars on specific vc
  BaseTools/Plugin/WindowsVsToolChain/WindowsVsToolChain.py
  pip-requirements.txt
Labels: language:python, impact:breaking-change, impact:non-functional

#1306 [Cherry-Pick] StandaloneMmPkg: Disable assert when gMmCommBufferHobGuid not found.
  StandaloneMmPkg/Core/StandaloneMmCore.c
Labels: impact:non-functional

#1305 [CHERRY-PICK] Revert Mu Change in Favor of edk2 Change
  BaseTools/Conf/tools_def.template
Labels: impact:non-functional
