Repository microsoft/mu_basecore, pull requests merged in 2025-04, with the labels that each got.

#1326 BaseTools/UefiVarPatcher: Add plugin
  BaseTools/Plugin/UefiVarPatcher/ReadMe.md
  BaseTools/Plugin/UefiVarPatcher/UefiVarPatcher.py
  BaseTools/Plugin/UefiVarPatcher/UefiVarPatcher_plug_in.yaml
Labels: language:python, impact:non-functional, type:documentation, type:backport

#1312 [Cherry-Pick] UefiCpuPkg: Enable MM_CORE_STANDALONE for IntelMmSaveStateLib, SmmCpuPlatformHookLibNull
  UefiCpuPkg/Library/MmSaveStateLib/IntelMmSaveStateLib.inf
  UefiCpuPkg/Library/SmmCpuPlatformHookLibNull/SmmCpuPlatformHookLibNull.inf
Labels: impact:non-functional, type:backport

#1332 Add MsegSize to the CPU_INFORMATION_HEADER struct
  MdePkg/Include/Register/Intel/StmApi.h
Labels: impact:non-functional

#1333 Add MsegSize to the CPU_INFORMATION_HEADER struct
  MdePkg/Include/Register/Intel/StmApi.h
Labels: impact:non-functional

#1337 [Cherry-pick] Fix a bug exposed in MM communicate v3
  MdeModulePkg/Core/PiSmmCore/PiSmmIpl.c
Labels: type:bug, type:backport

#1297 Add BuildReportEvaluation post build plugin
  .pytool/Plugin/BuildReportEvaluation/BuildReportEvaluationPlugin.py
  .pytool/Plugin/BuildReportEvaluation/BuildReportEvaluationReadMe.md
  .pytool/Plugin/BuildReportEvaluation/BuildReportEvaluation_plug_in.yaml
  .pytool/Plugin/BuildReportEvaluation/buildreport_table.py
  .pytool/Plugin/BuildReportEvaluation/queries.json
Labels: impact:non-functional

#1343 [Squash on Rebase] Update release-basetools to use newer ubuntu.
  .github/workflows/release-basetools.yml
Labels: impact:non-functional
