Repository microsoft/mu_basecore, pull requests merged in 2025-02, with the labels that each got.

#1274 [CHERRY-PICK] Fix lcov 2.0 in HostBasedUnitTestRunner [Rebase & FF]
  BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
Labels: language:python, impact:non-functional, type:backport

#1269 MdeModulePkg/Variable: Init var policy after SMM variable is ready
  MdeModulePkg/Universal/Variable/RuntimeDxe/VariablePolicySmmDxe.c
  MdeModulePkg/Universal/Variable/RuntimeDxe/VariableSmmRuntimeDxe.c
Labels: type:design-change

#1276 MdeModulePkg/UefiBootManagerLib: Register var policy on notify
  MdeModulePkg/Library/UefiBootManagerLib/BmBoot.c
Labels: type:design-change, type:backport

#1275 [CHERRY-PICK] MdePkg/IndustryStandard: Adds SPMI macros
  MdePkg/Include/IndustryStandard/ServiceProcessorManagementInterfaceTable.h
Labels: impact:non-functional, type:backport

#1278 BaseTools/ClangPdbToolChain: Improve CLANG_BIN guidance
  BaseTools/Plugin/ClangPdbToolChain/ClangPdbToolChain.py
Labels: language:python, impact:non-functional, type:backport

#1266 MdePkg: Add Google Mock Protocol for SmmCommunication
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockSmmCommunication.h
Labels: impact:non-functional, type:backport

#1277 [Cherry-Pick] MdePkg: Tpm2Acpi.h: Add defines for TPM2 ACPI table revision 5
  MdePkg/Include/IndustryStandard/Tpm2Acpi.h
Labels: impact:non-functional

#1280 ShellPkg: Removed EmptyParamList and SfoParamList from MockShellLib.cpp
  ShellPkg/Test/Mock/Library/GoogleTest/MockShellLib/MockShellLib.cpp
Labels: impact:non-functional, type:bug, type:backport

#1285 MdeModulePkg/SmmCorePerformanceLib: Remove offset from comm buffer dest space
  MdeModulePkg/Library/SmmCorePerformanceLib/MmCorePerformanceLib.c
Labels: type:bug
