Repository microsoft/mu_basecore, pull requests merged in 2025-01, with the labels that each got.

#1248 Added MockHiiLib, MockShellLib, MockHiiDatabase protocol
  MdeModulePkg/Test/MdeModulePkgHostTest.dsc
  MdeModulePkg/Test/Mock/Include/GoogleTest/Library/MockHiiLib.h
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockHiiLib/MockHiiLib.cpp
  MdeModulePkg/Test/Mock/Library/GoogleTest/MockHiiLib/MockHiiLib.inf
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockHiiDatabase.h
  ShellPkg/ShellPkg.ci.yaml
  ShellPkg/ShellPkg.dec
  ShellPkg/Test/Mock/Include/GoogleTest/Library/MockShellLib.h
  ShellPkg/Test/Mock/Library/GoogleTest/MockShellLib/MockShellLib.cpp
  ShellPkg/Test/Mock/Library/GoogleTest/MockShellLib/MockShellLib.inf
  ShellPkg/Test/ShellPkgHostTest.dsc
Labels: impact:non-functional, type:backport

#1252 [CHERRY-PICK] StandaloneMmPkg: Call PeCoffLoaderUnloadImage When Unloading Image
  StandaloneMmPkg/Core/Dispatcher.c
Labels: type:bug, type:backport

#1256 [Cherry-Pick] MdePkg: Add rest mock functions for Mock UefiRuntimeServicesTableLib
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiRuntimeServicesTableLib.h
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiRuntimeServicesTableLib/MockUefiRuntimeServicesTableLib.cpp
Labels: impact:non-functional, impact:testing, type:backport

#1145 BaseTools/OverrideValidation: Sort files prior to hashing.
  BaseTools/Plugin/OverrideValidation/OverrideValidation.py
Labels: language:python

#1264 Added MockShellCommandLib
  ShellPkg/Test/Mock/Include/GoogleTest/Library/MockShellCommandLib.h
  ShellPkg/Test/Mock/Library/GoogleTest/MockShellCommandLib/MockShellCommandLib.cpp
  ShellPkg/Test/Mock/Library/GoogleTest/MockShellCommandLib/MockShellCommandLib.inf
  ShellPkg/Test/ShellPkgHostTest.dsc
Labels: impact:non-functional, type:backport
